### ISSUE TITLE
Linear Regression Model And Mixed ANOVA with repeated Measures

### ISSUE THREAD

**Issue by ProfAthlete** [0todd0000/spm1d#103]
Hi, 
I'm curious on why the joint angle/moment regression models mentioned in some of the papers (i.e. Vanrenterghem 2012, Sankey 2015) are implemented and how they can be implemented in Python. Also, I am curious about what the Alpha, Beta, Theta and Epsilon refer to.

My research will be looking into effects of fatigue on trained/untrained athletic maneuvers, and I will be using within-between subjects' ANOVA with repeated measures in SPM1D (Python) for analysis. I am wondering if my research would need the implementation of the regression models. Could you please enlighten on the matter?

sincerely, Muhammad.

**Comment by 0todd0000** [comment]
Hi, sorry for the delay!

- Alpha = Type I error rate (usually 0.05)
- Beta = regression parameters (usually group means or regression slopes)
- Theta = (I'm not sure, do you have an example or citation?)
- Epsilon = residuals

> I'm curious on why the joint angle/moment regression models mentioned in some of the papers (i.e. Vanrenterghem 2012, Sankey 2015) are implemented and how they can be implemented in Python. 

"Why" is a tough question to answer, but it relates to the relevant study's purposes.  The easiest way to conduct these analyses in Python is to use the [**spm1d**](http://www.spm1d.org) package.  The best places to get started are (a) the example scripts in ./spm1d/examples, and (b) the [online documentation](http://www.spm1d.org/Documentation.html).

> My research will be looking into effects of fatigue on trained/untrained athletic maneuvers, and I will be using within-between subjects' ANOVA with repeated measures in SPM1D (Python) for analysis. I am wondering if my research would need the implementation of the regression models. Could you please enlighten on the matter?

If your independent variable(s) is/are continuous, then regression would likely be appropriate. Note that ANCOVA (i.e., ANOVA with regression) is not yet supported in **spm1d**.

**Comment by ProfAthlete** [comment]
Hi, I'm sorry for the confusion
what I mentioned as Theta was actually Tau. I'm shouldn't be so clumsy with these Greek symbols.

> If your independent variable(s) is/are continuous, then regression would likely be appropriate. Note that ANCOVA (i.e., ANOVA with regression) is not yet supported in spm1d.

I'll keep that in mind, In that case, would you recommend that I use a similar approach to [#12](https://github.com/0todd0000/spm1d/issues/12#issuecomment-104026767)'s issue?

**Comment by 0todd0000** [comment]
In Bayesian analysis Tau is usually the parameters whose values are to be estimated, but I'm not sure otherwise. If that's not what it is please send the name of the paper in which Tau appears.

Yes, the #12 approach (random effects modeling) might work well. Here is an [updated link](http://www.spm1d.org/doc/RandomEffects.html) to the documentation.

**Comment by 0todd0000** [comment]
I just realized: the symbols in Sankey et al. (2015) all refer to modeled parameters:

* Alpha:  regression intercepts
* Beta: regression slopes
* t (not Tau): time
* Epsilon:  residuals

Note that these symbols' meanings are specific to this paper. They don't necessarily mean the same thing in other papers.

**Comment by ProfAthlete** [comment]
>I just realized: the symbols in Sankey et al. (2015) all refer to modeled parameters:
Alpha: regression intercepts
Beta: regression slopes
t (not Tau): time
Epsilon: residuals

Oh my, I just realized that too. I also just realized that the Tau you used was not for any regression, but rather interaction effects in two-way ANOVA (Pataky et al. 2104; J Biomech)

>Note that these symbols' meanings are specific to this paper. They don't necessarily mean the same thing in other papers.

I see.  I will look further into the papers again and study them a little harder.
I'll reach out if I have some more (hopefully not so silly) queries. Thank you so much for your time explanations.

**Comment by ProfAthlete** [comment]
![image](https://user-images.githubusercontent.com/53344524/70451457-5a684200-1ae0-11ea-8fbc-a9cc0c7d0100.png)
Hi,
I was just wondering, what does "task execution variable" actually mean in this above regression equation and how do we actually define and implement it into the equation?

**Comment by 0todd0000** [comment]
I believe that this equation comes from [Sankey et el. 2015](https://www.sciencedirect.com/science/article/pii/S0966636215000831). If I am mistaken please cite its source.

My interpretation of this equation is:

* "Task execution variable" is an arbitrary dependent variable. In this paper it appears to represent a variety of scalar performance indicators.

* This equation can be implemented in a hierarchical random effects model, as described [here](http://www.spm1d.org/doc/RandomEffects.html).
