### ISSUE TITLE
One-sample t test. for champion data

### ISSUE THREAD

**Issue by yossy-biomech** [0todd0000/spm1d#106]
I have some questions about One-sample t test. In the spm1D homepage, I downloaded Slides_Booklet.pdf. In the slide ‘5. one subject, measured multiple times, compared to a “normal” database’ was shown in the Experimental scenarios.

My current research is analyzing champion athlete data. The champion athlete (n=1) and the control group (n=13) were participated. Kinematic data were measured by motion capture system. The trials were repeated 5 times by each participant. The positions of center of mass were calculated.

I would like to compare the movement of center of mass for the champion athlete with that for the control group by using One-sample t test in SPM.

Maybe, I need to use command,
>>> t  = spm1d.stats.ttest(Y. mu)
‘Y’ will be (13x101) for the normalized data of the control group.
It is difficult to understand ‘mu’.

Should I put (1x101) to ‘mu’ for the normalized data of the champion athlete?

**Comment by 0todd0000** [comment]
Yes, that sounds correct.

Setting `mu` to the mean for the champion athlete would test the following null hypothesis:

H0:  (mean Control group) = (mean Champion athlete)
