### ISSUE TITLE
One-sample t test. for champion data 2

### ISSUE THREAD

**Issue by yossy-biomech** [0todd0000/spm1d#107]
I have some questions about One-sample t test. In the spm1D homepage, I downloaded Slides_Booklet.pdf. In the slide ‘1. One subject, multiple trials, two tasks’ was shown in the Experimental scenarios.

My current research is analyzing champion athlete data as I mentioned in another question.

The champion athlete (n=1) was participated. He did two tasks, and repeated 5 times by each task. Kinematic data were measured by motion capture system. The positions of center of mass were calculated.

I would like to compare the movement of center of mass for the champion athlete between two tasks.
Should I use One-sample t test, or Two-sample t test in SPM?

If statistical analysis was used for one participant, does the analysis have meaning about statistics?

**Comment by 0todd0000** [comment]
> Should I use One-sample t test, or Two-sample t test in SPM?

It sounds like a two-sample test (**spm1d.stats.ttest2**) might be appropriate.  This would test the null hypothesis:

H0:  (mean Task A) = (mean Task B)

> If statistical analysis was used for one participant, does the analysis have meaning about statistics?

I would have statistical meaning, but that meaning would pertain to only this participant. The results would be relevant to this particular athlete, but not necessarily to anyone else.
