### ISSUE TITLE
Vector field analysis

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#11]
Dear Todd,

I was wondering if vector field analysis can be performed in spm1d, similar to the EMG paper you published? If so, which is the module for it?

Regards,
Bernard

**Comment by m-a-robinson** [comment]
Hi Bernard,

As we have been discussing via email, vector field analysis can be used for EMG however it is not currently available with the spm1d release, hence my offer to assist with any initial analyses. Todd will be able to give more of a specific release timeline for this code.

Regards
Mark



On 15 May 2015, at 13:07, bernard-liew <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Todd,

I was wondering if vector field analysis can be performed in spm1d, similar to the EMG paper you published? If so, which is the module for it?

Regards,
Bernard

—
Reply to this email directly or view it on GitHub<https://github.com/0todd0000/spm1d/issues/11>.

________________________________
Important Notice: the information in this email and any attachments is for the sole use of the intended recipient(s). If you are not an intended recipient, or a person responsible for delivering it to an intended recipient, you should delete it from your system immediately without disclosing its contents elsewhere and advise the sender by returning the email or by telephoning a number contained in the body of the email. No responsibility is accepted for loss or damage arising from viruses or changes made to this message after it was sent. The views contained in this email are those of the author and not necessarily those of Liverpool John Moores University.

**Comment by 0todd0000** [comment]
Hi Bernard,
As Mark indicates the relevant functions are not yet public;  they'll be available in spm1d v.0.3 (the next major release), which will be available for download later this year, likely before the end of the summer.
Todd
