### ISSUE TITLE
pip install vs easy_install

### ISSUE THREAD

**Issue by Peej1226** [0todd0000/spm1d#111]
I am interested in using the spm1d within some analysis I am doing.  I'm new to Python and have always used pip install to add packages.  

Are there known issues with using pip install?  I've never used easy_install before, is this done in the same way as pip install?

**Comment by 0todd0000** [comment]
There have been no issues reported with pip vs. easy_install.  If you prefer pip, note that you can also use it:
```
pip install spm1d
```

[Here is the link](https://pypi.org/project/spm1d/) to spm1d at PyPi.

**Comment by Peej1226** [comment]
Great thank you.
