### ISSUE TITLE
RM Anova results interpreting

### ISSUE THREAD

**Issue by Vh2m** [0todd0000/spm1d#112]
Hi Todd.
First of all thanks a lot for the great work,
I am trying to identify whether there are differences for lower limb kinematics and joint moments for a step reaction between two ground conditions. Participants performed 10 steps (each one is an independent observation in time, this is not locomotion but a postural reaction) onto two different surfaces. I am also interested in assess is there are any differences within each condition. So, what would be your recommendation to perform such comparison?
I know could use a paired t.test with the average of each participant per condition, but then I will loose any information of within condition. A one way rmANOVA is a within design, but when I run spm1d.anova1rm I get a within and a between subject model. It might be semantic but what are these models referring to? As far as I know one should be testing differences column-wise and the other row-wise, but with data been an array I am a bit lost. Could you guide me out here?
Thanks!

**Comment by 0todd0000** [comment]
Hi!

> I know could use a paired t.test with the average of each participant per condition, but then I will loose any information of within condition

By "within condition differences", do you mean differences amongst participants? The intra-subject variability within a single condition?

> when I run spm1d.anova1rm I get a within and a between subject model

I don't quite understand, does the software return a between-subjects model?  It should only return a within-subjects model.  If there are only two conditions, this model should be equivalent to a paired t test model.

**Comment by Vh2m** [comment]
Hi todd.
Thanks for the quick response.

> By "within condition differences", do you mean differences amongst participants? The intra-subject variability within a single condition? 

Exactly

> I don't quite understand, does the software return a between-subjects model? It should only return a within-subjects model. If there are only two conditions, this model should be equivalent to a paired t test model.

I was checking the example and it has a between and within model. I just realised though that it uses both anova1 and anova1rm comands which pretty much explain the double model.

**Comment by 0todd0000** [comment]
Hi again,

> I was checking the example and it has a between and within model. I just realised though that it uses both anova1 and anova1rm comands which pretty much explain the double model.

OK, I see now. Yes, that example is meant to illustrate between- vs. within-subjects models. Only one must be chosen. **spm1d.stats.anova1rm** itself uses a within-subjects model.

**Comment by Vh2m** [comment]
Thanks again for the clear explanation. Any ideas how to approach the intra-subject variability within a single condition?

**Comment by 0todd0000** [comment]
It depends what the hypothesis is. If the hypothesis pertains to Condition effects, then intra-subject variability is largely irrelevant. An intra-subject mean can usually be used as an unbiased estimator of that subject's true mean, especially in Biomechanics, where **inter-** subject variability is much larger than **intra-** subject variability.

**Comment by Vh2m** [comment]
And if I would be interested in see if there is an effect of number of performed repetition (due to an acute learning effect)?

**Comment by 0todd0000** [comment]
Then the design would be a considerably more complicated ANCOVA design. There would be two factors: CONDITION (categorical variable) and TIME (continuous variable), with possible interactions amongst these factors (e.g. performance increases across time in one condition, and performance decreases in the other condition). ANCOVA designs like this are not currently supported in **spm1d**

**Comment by Vh2m** [comment]
Thank a lot Todd, This has been very helpfull.
