### ISSUE TITLE
z scores instead of t scores

### ISSUE THREAD

**Issue by limbicode214** [0todd0000/spm1d#114]
Hi Todd

We performing a multiple regression analysis using 
t      = spm1d.stats.glm(Y, X, c)  
ti     = t.inference(0.05)

How can we display z, instead of t scores ? By simply replacing the "t" with "z" it still shows spm {t} on the y-axis and we are not sure if those are the z-scores within a significant cluster as they are very similar with a sample size > N = 30. 

many thanks for your help, michael

**Comment by 0todd0000** [comment]
Hi!  z scores have to be manually calculated. For single samples this is easy:

```python
import numpy as np

y = np.random.randn(8, 101)  

z = (y - mu) / sigma # if population mean & SD are known
z = (y - y.mean(axis=0)) / y.std(axis=0, ddof=1) # if population mean & SD are unknown
```

In regression designs I believe that z scores can be calculated from correlation coefficients, so you'd first need to calculate the correlation coefficient of interest, then calculate the z score.

**Comment by limbicode214** [comment]
Many thanks Todd. I simply calculated the correlation coefficient for each t-value (from spm.z) using the formula R2 = t2 / (t2 + DF)
