### ISSUE TITLE
One sided t-tests

### ISSUE THREAD

**Issue by mike214999** [0todd0000/spm1d#115]
Dear SPMlers

After some time I realized that my significant results were always two-tailed instead of one-tailed (that fits my hypothesis). 
However, when using 
ti     = t.inference(0.05, two_tailed=False)
it seems that it only tests in one direction as the result is not significant anymore. 
How can I instruct the model to test in the opposite direction ? 

Thanks for help! 
Chris

**Comment by cedricmorio** [comment]
Have you tried to switch yA and yB params? Because as you have a directional hypothesis, you should always put the data in a specific order.
