### ISSUE TITLE
Plot Individual Spmi P Values on Graph

### ISSUE THREAD

**Issue by SHughes93** [0todd0000/spm1d#127]
[http://spm1d.org/doc/API/plot.html](url)

**spm1d.plot.plot_spmi_p_values(spmi, ax=None, size=8, offsets=None, offset_all_clusters=None, autoset_ylim=True)**

This code provides the ability to plot all P values next to all clusters on the graph. Is it possible to plot only specific P values next to specific clusters instead of all?

**Comment by m-a-robinson** [comment]
Hello,
I don't _think_ this is possible using the default plotting function you describe unless there is a way to specify the specific cluster of interest from the spmi object I don't know of. 
You can of course not use this function and manually add the desired p-values yourself using the [text ](https://matplotlib.org/3.1.0/api/text_api.html?highlight=add%20text) or [annotate](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.annotate.html?highlight=annotate#matplotlib.pyplot.annotate) commands should you wish.
Regards
Mark

**Comment by SHughes93** [comment]
Good point about adding the desired p-values manually. I may have to go this route and hopefully can replicate the automatic P-values on the adjacent subplots so it doesn't look out of place.
