### ISSUE TITLE
Exact value where data exceed threshold

### ISSUE THREAD

**Issue by annabednarska** [0todd0000/spm1d#128]
Hi all,
I am looking for the way to find exact value of x (Time (%)) where data exceed a threshold. 
How can I do this?
Ideally if it is possible to draw the line on the plot like the green one in example below:

![image](https://user-images.githubusercontent.com/13101853/81830086-eec94b80-953b-11ea-9d4a-4333012d78cc.png)

Thank you for help in advance.

**Comment by m-a-robinson** [comment]
Hello,

You can find this in "clusters" with the "endpoints" keyword. Cluster details are stored in the inference object (usually referred to in the example code as ti or spmi).

Example to print details of all clusters, this gives you an overview of all cluster-related information.
`print(ti.clusters)`

Example to print the detials of the first [0] cluster endpoints only
`ti.clusters[0].endpoints`

Once you know the exact x-axis location, you can use this to draw your vertical line in the correct place. Check out [axvline](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.axes.Axes.axvline.html)

Regards
Mark

**Comment by annabednarska** [comment]
Thank you a lot!
