### ISSUE TITLE
Non-parametric and normality tests in SPM

### ISSUE THREAD

**Issue by gabrielmoisan** [0todd0000/spm1d#129]
Hi Todd,
Do you have a list of all the non-parametric and normality tests that can implemented in SPM?
For example ANOVA1rm=permutation test (Nichols and Holmes 2002).
I'd like to know for the following, but a complete list could help others:

Non-parametric equivalent:
-dependent and independent t tests
-One way Anova
-Hotelling's paired
-nonparam.hotellings2

Normality tests:
-dependent and independent t tests
-One way Anova
-Anova1rm

Thanks again Todd,
Gabriel

**Comment by 0todd0000** [comment]
Hi Gabriel,

Nonparametric and normality tests are supported for all tests in **spm1d.stats**.

So if you have run a test called **spm1d.stats**.*testname*, there are corresponding nonparametric and normality tests called:
* **spm1d.stats.nonparam**.*testname*
* **spm1d.stats.normality.k2**.*testname*
* **spm1d.stats.normality.sw**.*testname*

All nonparametric tests use permutation.

The normality tests use either the D'Agostino-Pearson K2 test (**normality.k2**) or the Shapiro-Wilks statistic (**normality.sw**). Both **k2** and **sw** procedures are corrected for arbitrary one-dimensional domains using random field theory.

Todd

**Comment by gabrielmoisan** [comment]
Thanks Todd!
