### ISSUE TITLE
Installation of SPM1d.03- download location

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#13]
Dear Todd,

I noticed that spm1d.03 is out. I was wondering where the zip file for download and installation is?

When installing v3, must I remove the old version and replace with the new file?

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

As of version 0.3 the source code is available here on github:
https://github.com/0todd0000/spm1d
You should see a link "Download ZIP" on the lower right.

However, if you already have Python installed it is easier to download and install the source code by running the following command from a Terminal or Command Prompt:
```
easy_install spm1d
```
This will automatically download and install **spm1d** and its dependencies (like **rft1d**).

Please find detailed installation instructions here:
http://www.spm1d.org/install/InstallationPython.html#label-installationpython

Old versions of **spm1d** can remain installed, just make sure you import the correct version. To check the version type:
```
import spm1d
print spm1d.__version__
```
The version should be 0.3.x

Todd

**Comment by bernard-liew** [comment]
Hello Todd,


many thanks for your help, as always... Followed the website's instructions, error below pops up (see image too)..

"%run "c:\users\14342453\appdata\local\temp\tmp0h17u7.py"
  File "c:\users\14342453\appdata\local\temp\tmp0h17u7.py", line 1
    easy_install spm1d
                     ^
SyntaxError: invalid syntax
"
![spm1d 03](https://cloud.githubusercontent.com/assets/12288089/8521188/f67871ce-2413-11e5-8ef8-74d391e720ea.PNG)

regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

You need to run "easy_install" in a Terminal (Mac, Linux) or in a Command Prompt (Windows), not inside Canopy.  "easy_install" is standalone software.

Open a Command Prompt:
http://windows.microsoft.com/en-US/windows-vista/Open-a-Command-Prompt-window

Then type:
```
easy_install spm1d
```
 
Todd

**Comment by millysfabrielle** [comment]
Hello,

I'm trying to use SMP1D to analyze some datas, however I'm having some troubles to run some examples provided.

I just followed the instalation as show in tutorial (http://www.spm1d.org/install/InstallationPython.html). 
![install](https://cloud.githubusercontent.com/assets/4121237/8527829/3ade1532-23e5-11e5-8527-e456d9aa547c.png)

After that i just tried to execute some examples according to (http://www.spm1d.org/NewFeatures.html#label-newfeatures), however I always recive same error.

![execution](https://cloud.githubusercontent.com/assets/4121237/8527940/087bf752-23e6-11e5-8a1e-83cc905c86cf.jpg)

Should I have to install additional modules or do some extra configuration ?

**Comment by bernard-liew** [comment]
Dear Todd,

Worked like a gem the installation.. Many thanks :)

However,
Like Milly, when I tried to run some examples, I have the following error

%run "c:\users\14342453\appdata\local\temp\tmprpvcxr.py"
0.3.0 (2015/07/01)

%run "C:\Users\14342453\AppData\Local\Temp\spm1d03\spm1d\stats\manova.py"
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Users\14342453\AppData\Local\Temp\spm1d03\spm1d\stats\manova.py in <module>()
      5 from math import sqrt,log
      6 import numpy as np
----> 7 import _mvbase
      8 import _spm
      9 

C:\Users\14342453\AppData\Local\Temp\spm1d03\spm1d\stats\_mvbase.py in <module>()
      3 import numpy as np
      4 from scipy import ndimage
----> 5 import _spm
      6 import rft1d
      7 

C:\Users\14342453\AppData\Local\Temp\spm1d03\spm1d\stats\_spm.py in <module>()
     16 import numpy as np
     17 from scipy import ndimage,optimize,stats
---> 18 from .. plot import plot_spm, plot_spm_design
     19 from .. plot import plot_spmi, plot_spmi_p_values, plot_spmi_threshold_label
     20 import rft1d


Do I need additional installation?

Bernard

**Comment by 0todd0000** [comment]
Hi Milly,

Thanks for reporting the problem.  It seems like the **rft1d** version is not the latest.
Please try this:

First update **rft1d** using the following command:

```
easy_install rft1d
```

Then try running the example again.

Let me know if that doesn't solve things.

Todd

**Comment by 0todd0000** [comment]
Hi Bernard,
It appears that you're attempting to run the module **\spm1d\stats\manova.py** as a script.
**manova.py** is not a script so can't be executed directly (it contains functions which scripts can access).
Please try running the scripts in **\spm1d\examples** .
Todd

**Comment by bernard-liew** [comment]
Thanks Todd,

Same problem as Milly. What version should rft1d be? Mine says v0.1.1

**Comment by 0todd0000** [comment]
Hi Bernard,
The most recent version of **rft1d** is "0.1.2.1"

Try updating to the most recent version using:
```
easy_install rft1d
```
If that doesn't work try force-installing the most recent version using:
```
easy_install rft1d==0.1.2.1
```
Todd

**Comment by 0todd0000** [comment]
I'll assume that the **rft1d** update solved the installation problems, but please let me know if it didn't and I'll re-open this issue.
Todd

**Comment by millysfabrielle** [comment]
Hello,

I fixed this problem updating rft1d manually.
1) I downloaded the files provided by this page (https://github.com/0todd0000/rft1d)
2) I extracted and put in the folder:
C:\Users\<YOU USER HERE>\AppData\Local\Enthought\Canopy\User\Lib\site-packages

This is folder is because, as suggested by the tutorial I'm using Canopy.

**Comment by 0todd0000** [comment]
Hi Milly,
Did that installation method work?
If not, please use the easy_install method instead.
Todd

**Comment by bernard-liew** [comment]
Thanks Todd,

Mine is alright, although I had to use another method. Rft1d version kept coming up as the older version.

In the command window i ran pip_uninstall rf1td first. than easy_install rft1d. and the new version was imported.

Regards,
Bernard

**Comment by 0todd0000** [comment]
Thanks very much for the feedback, Bernard,

**Comment by millysfabrielle** [comment]
I did not try to force **easy_install rft1d==0.1.2.1**. However updating manually worked to me.
