### ISSUE TITLE
How to calculate Power for SPM tests

### ISSUE THREAD

**Issue by Little-Foot-Shapes** [0todd0000/spm1d#131]
Hi Todd, 

I was wondering if you have the power calculation sorted for SPM1D as you mentioned in one of your previous posts here? I would be using it for non-parametric tests.

Thank you.

Best Regards

Mat

**Comment by 0todd0000** [comment]
Hello Mat,

Yes, power calculations are available, but not directly as part of the main spm1d package:
http://spm1d.org/power1d/

The paper below discusses these calculations in more detail:
https://peerj.com/articles/cs-125

Todd

**Comment by Little-Foot-Shapes** [comment]
Hello Tod, 

Thank you for your quick response. I guess there is no Matlab version yet then....have you got any plans making a Matlab version?

Thank you.

Best Regards

Mat

**Comment by 0todd0000** [comment]
Hi Mat,

No, there are no plans for a Matlab version at this time. The main reasons are that (a) there is no suitably robust random number generator (RNG) for Matlab, where the RNG generates smooth Gaussian 1D datasets, and (b) developing a suitable RNG would require Matlab's Statistics Toolbox. We want to make sure that all **spm1d** features remain free of paid add-ons.

The Python RNG is working well, has been validated externally, and does not require any paid add-ons.

Todd

**Comment by Little-Foot-Shapes** [comment]
Great, thank you!
