### ISSUE TITLE
PRE-POST Training effects

### ISSUE THREAD

**Issue by asansix** [0todd0000/spm1d#132]
Hi Todd,

I have 2 groups of 10 participants that performed countermovement jump before and after (PRE – POST) two different interventions. I have the force-time and velocity-time curves. I want to know, the effect of each group after the intervention (within-subjects) and the interaction between the training effects. I used Matlab software and I conducted the SPM1d_anova2onerm_2x2 analysis, is it ok? 

The results showed no interaction but there were differences in the main B effect. Then, in order to know the differences after the intervention for each group I conducted the SPM1d_ttest_paired, is it ok?

The paired t-test showed no differences in one intervention group but showed differences in the other intervention group. 

![Paired t-test Group B velocity-time curve](https://user-images.githubusercontent.com/66722281/84246406-e21e2000-ab06-11ea-8ec5-afa3dd898405.jpg)
![ANOVA 2x2 Velocity-time curves](https://user-images.githubusercontent.com/66722281/84246409-e34f4d00-ab06-11ea-9938-373527090af7.jpg)
![Paired t-test Group A velocity-time curve](https://user-images.githubusercontent.com/66722281/84246411-e34f4d00-ab06-11ea-9cc0-430e8f855a6a.jpg)

Thank you so much for all your contributions and the facilities given in the web.

Alberto.

**Comment by 0todd0000** [comment]
Hi Alberto,
Using **spm1d.stats.anova2onerm** is fine if the two interventions involved different participants. Everything else sounds good!
Todd

**Comment by asansix** [comment]
Hi Todd, 
thank you for your answer. Yes, there were different participants in each group. 
Alberto.
