### ISSUE TITLE
Repeated measures MANOVA

### ISSUE THREAD

**Issue by odandridge** [0todd0000/spm1d#134]
Dear Todd,

I have a dataset of knee kinematics that I would like to analyse using SPM1D. For 8 subjects, I have 5 dependent variables, 2 tibiofemoral rotations (ext rotation and varus) and 3 translations (lateral, anterior, and 'distal'), measured at 1 deg intervals between 0-110 flexion. My groups are made up of four treatment 'states' (native, arthroplasty1, arthroplasty2, arthroplasty3). I think I should use the non-para version thanks to small sample size but any comment otherwise is appreciated.

I think it might be worthwhile to use a multivariate approach. It doesn't make complete sense to me to look at joint motions separately, unless there is a specific hypothesis, for example, "arthroplasty1 results in less external rotation than arthroplasty2 but not arthroplasty3".

Not using S(n)PM, I think this requires in a two-way (state and flexion angle) mixed repeated measures MANOVA but this is rather clumsy and appears difficult to set up in SPSS, even when flexion interval is increased to say 5 or 10 deg. 

Using S(n)PM, reduces it to a one-way repeated measured MANOVA, I think. Is this possible using the toolbox or some adaption of it? I would also be grateful if you could comment on my selection of test and if you have alternative recommendations. Generally, SPM is appealing as I am comparing waveforms where differences might be quite subtle and dispersed throughout the flexion range. Bonferroni (or less severe) correction after scalar extraction has proved too harsh.

Thanks,
Oli

**Comment by odandridge** [comment]
I should add that if dependent variable units must be consistent, I think it would be acceptable to split the study in two, investigation rotations and translations separately.

Thanks,
Oli

**Comment by 0todd0000** [comment]
Hi Oli, thank you for this question!

Easy part first:
The dependent variables needn't have consistent units, nor even be physically similar. To demonstrate this, multiply one of the variables by 100 or 1000, and re-run analyses. The results should be consistent. The mathematics are the same whether the units are radians, degrees, millimeters, meters, newtons or pounds, etc., provided the units are consistent within a single DV of course.

Regarding the design:
One-way RM MANOVA sounds appropriate, but this is unfortunately not yet supported in **spm1d**. You can get around this relatively easily, by jumping to *post hoc* -like tests: paired Hotelling's T2 tests on individual treatment pairs, with a Bonferroni correction across the paired tests. This isn't robust *post hoc* analysis, but it is approximately correct, and I don't expect that reviewers would have a problem with this approach unless there are borderline effects.

Todd

**Comment by odandridge** [comment]
Thanks very much for this info and your quick reply.

So, just to clarify, you think the one-way MANOVA capability in spm1d can approximate a one-way repeated measures MANOVA, provided post-hoc tests are then used as rigorously as possible? I also feel that reviewers will accept such a post-hoc analysis, my concern was getting around the lack of repeated measures capability in the MANOVA program. I guess generally I am not crystal clear on the effect of repeated measures when it comes to MANOVA! Do you think enhanced MANOVA capability will be added?

Thanks again,
Oli

**Comment by odandridge** [comment]
As a follow up question to save time if I do go ahead with the 1-way MANOVA as it is:

How should I go about setting up the data? The example is an 8x100x3 matrix, which as I understand is 8 trials (2 of each speed) x 100 nodes x 3 vector components.

Unless I have completely misunderstood what you mean by 'jump to post hoc tests' and you meant to ignore the MANOVA entirely, assume differences are picked up, and just use post hoc tests immediately with correction?

Thanks,
Oli

**Comment by 0todd0000** [comment]
> So, just to clarify, you think the one-way MANOVA capability in spm1d can approximate a one-way repeated measures MANOVA

No, this is incorrect. Do not use one-way MANOVA. Use paired Hotelling's T2 tests.
(I think this addresses your follow-up question.)

> Do you think enhanced MANOVA capability will be added?

Yes, additional features including m-way MANOVA and MANCOVA will eventually be available in **spm1d**. Here is our current development list:
https://github.com/0todd0000/spm1d/issues/45
