### ISSUE TITLE
Statistical power1d computation

### ISSUE THREAD

**Issue by AlbertoNTC** [0todd0000/spm1d#136]
Hello Professor Pataky, 

I want to estimate the statistical power of my data. I have 2 samples with 9 subjects each, and 5 dependent variables (5 joint angles). In this case, What is the procedure to estimate the statistical power1d for these data sets? 

Also, since I have 5 DV, Should I test for only one of them or all 5? 

Thank you in advance, 
-Alberto Sanchez

**Comment by 0todd0000** [comment]
Hello Alberto,

It depends what type of power analysis you mean: *a priori* or *post hoc*...

For *a priori* power analysis, you'd also need:
* a definition of a 1D effect that would cause you to reject the null hypothesis.
* an estimate of the 1D variance, from a pilot experiment and/or from the literature.
An example of this type of power analysis for a two-sample test can be found here:
https://spm1d.org/power1d/Examples/PowerAnalysis.html#two-sample

For *post hoc* analysis:
* No software that I know of supports *post hoc* power analysis for 1D data.
* There is debate in the literature whether *post hoc* power analysis is valid. The general consensus is that it is not valid, although I appreciate that some reviewers request it and some software packages support it. Regardless, there are currently no plans to support *post hoc* power analysis in **spm1d**.

Regarding 5 DVs:
* I suggest starting with just a single DV (i.e., a univariate DV).
* Once you become familiar with the univariate DV procedure, then consider power analysis for a multivariate DV.
* There are two main difficulties with multivariate power analysis:
    * In addition to estimating 1D variance, you will also need to estimate 1D *co*variance (i.e., how the DVs correlate, and how this changes over the 1D domain).
    * You will need to define a multivariate effect.
    * These two steps are difficult, and I don't know of any precedent in the literature that you could follow. One way that it could be done is through musculoskeletal model optimization, which could be used to predict multivariate 1D outcomes.

So overall I'd recommend (a) *a priori* power analysis to calculate sample size, and (b) a univariate DV.  Pursuit of *post hoc* and/or power analysis for multivariate 1D DVs may require theoretical development and validation.

Todd
