### ISSUE TITLE
May I use two-way Anova with 1rm with groups of different size?

### ISSUE THREAD

**Issue by MarcusFV** [0todd0000/spm1d#138]
Hi Toddy,
  I have several variables of a foot model collected during running before and after some intervention.
  I have two groups: control and experimental. Control group did not undergo the intervention.
  My first choice was two-way Anova with 1rm: two groups (control and experimental) and two instants (before and after intervention).
  As post-hoc tests, I am using independent t test to compare the groups at each instant, and paired t test to compare instants for each group.
  However, some results do not make sense. Anova returns no significant results, for example, but post-hoc tests do.
  There is a small difference between group sizes: control group has 47 individuals, and experimental group 42 individuals.
  Can this difference explain these discreptant results?
  For repeated measures, I am taking 5 running cycles for each individual in each instant (before and after intervention). 
  Should I take only one average running cycle for each variable?
  As I have only two groups, and only two instants, two-way Anova with 1rm is a suitable statistical design?

  Or should I use another test?
  Most variables has two (X, Y) or three components (X, Y, Z).
  Maybe, I should use two-sample Hotelling test followed by independent t test as post-hoc test (for each variable component) for comparing groups in the instants before and after intervention.
  And paired Hotelling test followed by paired t test as post-hoc test for comparing before and after instants for each group.

  What would be the correct/best statistical test to be used in this study?
  If I use two Hotelling tests as suggested above, should I correct the p value for Hotelling tests? Or only for post-hoc tests?

  I would appreciate your help.
  And I thank you in advance.
Regards,
Marcus

**Comment by 0todd0000** [comment]
> There is a small difference between group sizes: control group has 47 individuals, and experimental group 42 individuals.
Can this difference explain these discreptant results?

A group size difference would likely not be responsible for this difference by itself.

> As post-hoc tests, I am using independent t test to compare the groups at each instant, and paired t test to compare instants for each group.

This sounds fine, provided you use a correction for the multiple *post hoc* tests. See here:
https://spm1d.org/doc/PostHoc/anova.html

> For repeated measures, I am taking 5 running cycles for each individual in each instant (before and after intervention).
Should I take only one average running cycle for each variable?

Yes, I recommend using only within-individual averages.

> As I have only two groups, and only two instants, two-way Anova with 1rm is a suitable statistical design?

Yes, **spm1d.stats.anova2onerm** is suitable.

> Most variables has two (X, Y) or three components (X, Y, Z).

It sounds like the dependent variables (DVs) are multivariate (i.e., vectors, not scalars), and that there is more than one multivariate DV. There are several things to consider.

* Analysis of multivariate DVs requires multivariate techniques like Hotelling's tests and MANOVA.
* ANOVA and t tests are univariate techniques and are generally unsuitable for multivariate DVs.
* SPM works only for a single DV (i.e., a single univariate DV or a single multivariate DV); when separately testing multiple DVs, one should correct for these multiple tests. 
* From your descriptions it sounds like *one-way repeated measures MANOVA* would be most suitable for a **single multivariate DV**.
* Unfortunately  *one-way repeated measures MANOVA* is not yet implemented in **spm1d**.
* It may be very difficult or impossible to robustly deal with several multivariate DVs.
    * One approach is to combine all DVs into a single multivariate DV.
    * However, this is non-ideal because a very large number of individuals will be needed to accurately estimate the covariance amongst the DV components. 
    * Another approach is to conduct separate multivariate tests, one for each variable, and to correct for these multiple tests.
    * However, this is also non-ideal because it ignores the potential correlation amongst the multiple DVs.

For your experiment I would recommend the following:
* Use multivariate techniques.
    * First correction: correct across the *N1* multivariate DVs.
* Conduct two separate paired Hotelling's tests to compare CONDITION (before vs. after), one test for the control group and one test for the intervention group.
- Conduct a two-sample Hotelling's test to compare the control and intervention groups 
    * Second correction: correct across these three Hotelling's tests (two paired tests and one two-sample test).
* Conduct *post hoc* tests using paired and two-sample t tests, similar to the Hotelling's strategy above.
    * Note that these *post hoc* t tests are only approximate explanations of the multivariate results, and that discrepancies in the *post hoc* vs main results are explainable by inadequate *post hoc* procedures.
    * Third correction:  correct across all *post hoc* tests

Last, please note:
* This type of experiment (many multivariate DVs) is quite common in biomechanics experiments and in the literature
* There is unfortunately no good way to use hypothesis testing (like SPM) to robustly deal with many multivariate DVs
* The advantages of hypothesis testing become clearer the more specific the hypothesis is, and thus the more specific the DV becomes
* When there are many multivariate DVs, the experiment may be inherently exploratory;  for exploratory experiments it may be better to use dimensionality reduction techniques like PCA and/or machine learning techniques like clustering

Todd

**Comment by MarcusFV** [comment]
Thank you very much, Todd (sorry not writing correctly your name previously).
I'll perform the Hotelling tests. I will return you the results as soon as possible.

Concerning using an average running cycle. I collected aroung 42 running cycles for each individual, discarching the first ones and the last ones. I have used 3 average running cycles (mean of 14 + mean of 14 + mean of 14)
You have recommended to use only one average running cycle. This was my first decision. But, SPM return this warning message when using 1rm:

Warning: Only one observation per subject found.  Residuals and inference will be
approximate. To avoid approximate residuals: (a) Add multiple observations per subject and
per condition, and (b) ensure that all subjects and conditions have the same number of
observations.

Can I ignore this warning and use only one average running cycle?

By the way, is there an easy way to plot two-way Anova results in only one row inside a figure? SPM two-way Anova plots main effects in one row and interaction effect in other row (I am referring to the subplots). It is hard work to move the subplots in order to plot main effects and interaction effect in only one row, so that the post-hoc tests can be plotted in the subsequent rows. 

Thank you again.
Good Night (here in Brazil is 1:30 AM!)
Best,
Marcus

**Comment by 0todd0000** [comment]
> Thank you very much, Todd (sorry not writing correctly your name previously).

No problem!

> Can I ignore this warning and use only one average running cycle?

Yes, you can ignore this warning. Try both ways: (1) with one mean observation per individual, and (2) with multiple observations per individual. If you have set up the analyses correctly, the results should be practically identical.

> By the way, is there an easy way to plot two-way Anova results in only one row inside a figure? 

Yes, the easiest way is to use the [subplots](https://matplotlib.org/3.3.0/api/_as_gen/matplotlib.pyplot.subplots.html) command like this:

```python
from matplotlib import pyplot as plt
import spm1d


#(0) Load data:
dataset      = spm1d.data.uv1d.anova2.SPM1D_ANOVA2_2x2()
Y,A,B        = dataset.get_data()


#(1) Conduct ANOVA:
alpha        = 0.05
FF           = spm1d.stats.anova2(Y, A, B, equal_var=True)
FFi          = FF.inference(alpha)


#(2) Plot results:
plt.close('all')
fig,ax = plt.subplots(1, 3, figsize=(12,3))
for axx,Fi in zip(ax,FFi):
    Fi.plot(ax=axx)
    Fi.plot_threshold_label(ax=axx)
    Fi.plot_p_values(ax=axx)
plt.setp(ax[1:], ylabel=None)
ax[0].set_title('Main A')
ax[1].set_title('Main B')
ax[2].set_title('Interaction AB')
plt.show()
```

![fig](https://user-images.githubusercontent.com/4276626/89975757-89533b00-dca1-11ea-9829-4c29ec500962.png)

**Comment by MarcusFV** [comment]
Thank you, Todd.
Best,
Marcus
