### ISSUE TITLE
2D1D data analysis possibilities

### ISSUE THREAD

**Issue by fanicio** [0todd0000/spm1d#149]
Hello, I would like to perform a 2D analysis with two joint angles time-series that are related to foot pronation (rearfoot-shank motion in the frontal and transverse planes). I was wondering if I can consider the joint angles as positions in space (space-domain) and their resultant vector as values varying through time (time-domain). Thank you.

**Comment by 0todd0000** [comment]
It is possible, but only if the 2D domain is adequately sampled, and preferably in a controlled manner.

Here is my understanding of your question, please correct me if I am wrong:

* A typical, multivariate SPM analysis of these data would regard the domain Q as one-dimensional time, and the two dependent variables (joint angles) as Y1 and Y2.
* I believe that you are suggesting to instead regard the joint angles as a two-dimensional domain (Q1, Q2), where Q1 and Q2 represent the joint angles. This is fine, in general, provided you adequately sample the (Q1,Q2) space, preferably in a controlled manner. Theoretical and numerical problems will arise if not every point in (Q1,Q2) space has the same number of observations. If there are 10 observations at one point, and 5 at another, and 20 at another, for example, it will be very difficult to analyze the data. SPM analyses generally require an equal number of observations at all domain points. There are a variety of methods described in the FDA literature that are not restricted in this manner.
* However, in this case I don't quite understand what the dependent variable is. From my understanding, the resultant vector (q1,q2) is a position on the domain. There needs to be a separate, (univariate or multivariate) dependent variable.

**Comment by fanicio** [comment]
Thanks for your reply. Our data were exported by the Visual3D, so it is already time-normalized to 101 points. I intend to use the joint angles of the frontal (angles_1) and transverse (angles_2) planes of motion as Q1 and Q2 and their combined values (angles_1 + angles_2, or RMS(angle1,angle2) for example) as Y. I though in using the resultant angles between frontal and transverse planes because the foot pronation during the midstance of gait is combined motion between all three planes of motion, mainly these two.  Therefore, I understand that, in this case, Q1 and Q2 could be in the space-domain (ie. joint positions in space), and their combined values varying along the time (time-domain). If this is possible, I would like to run a 2D1D analysis with these data, similarly to that of your using the baropodometry.

**Comment by 0todd0000** [comment]
There are two issues to consider:

1. **Lack of DV independence**. Since the dependent variable (DV) is not independent of (Q1, Q2), there are some serious statistical concerns regarding serial correlations. This is not easy to solve.

2. **Sampling of the 2D domain**. In order to construct the 2D domain, you must sample (Q1, Q2) over regular intervals. This is easy for devices like pressure plates and MRI scanners, which are designed to sample at regular spatial intervals. In this situation I don't think it would be possible to regard (Q1, Q2) as having been sampled at controlled, regular intervals.
