### ISSUE TITLE
error in example : ex_anova1_posthoc.py

### ISSUE THREAD

**Issue by fablebGitHub** [0todd0000/spm1d#15]
hi 

i have notice a small error in ex_anova1_posthoc.py. 

you have to replace the line 
Y0,Y1,Y2     = [Y[A==u] for u in np.unique(A)]
by 
Y1,Y2,Y3     = [Y[A==u] for u in np.unique(A)]

regards

fabien

**Comment by 0todd0000** [comment]
Hi Fabien,
Thanks very much for spotting the error. The file is now updated at github.com and should also be updated automatically if you run:
```easy_install spm1d```
Thanks again,
Todd
