### ISSUE TITLE
Saving spm1d figures as .fig 

### ISSUE THREAD

**Issue by Sonyht** [0todd0000/spm1d#150]
Is there a way, to save spm1d graphs and figures as .fig format, or any other format that you can edit post facto without any programming knowledge (fonds, fond-size etc.)?

I already saved a file as .svg through the savefig function of matplotlib, but was wondering if there is a better way, since i can't open  the svg in Excel, or do not have any information on the Data.

**Comment by 0todd0000** [comment]
The easiest way to create FIG files is to use the Matlab version of **spm1d**:
https://github.com/0todd0000/spm1dmatlab
https://spm1d.org/DocumentationMatlab.html

If you don't have Matlab, then try using *savefig* to save the figure in EPS format; this format should be readable and editable in vector graphics software packages.

Here is a relevant discussion on stackoverflow:
https://stackoverflow.com/questions/23088303/python-matplotlib-how-to-automatically-save-figures-in-fig-format
