### ISSUE TITLE
Is four-way ANOVA possible in spm1d?

### ISSUE THREAD

**Issue by 0todd0000** [0todd0000/spm1d#151]
Is four-way ANOVA possible in spm1d?

{This is a paraphrased question that arose in a discussion outside of this forum.}

**Comment by 0todd0000** [comment]
Four-way and higher-order ANOVA is unfortunately not supported in the current version of **spm1d** (version 0.4). 

If responding to reviews, I'd suggest saying that **spm1d** is currently in relatively infant stages (version 0.4) compared to established platforms like R and SAS, and does not yet support arbitrary linear modeling. Arbitrary linear modeling, inclufing four-way and higher-order ANOVA, MANOVA and MANCOVA will be supported in future versions of **spm1d**.

**Comment by FaSergi** [comment]
Thanks Todd for posting this question on the forum. And thanks so much for developing such useful code and making it available to the community. I have a follow-up question. 

I have had reviewers point out to the fact that a dedicated statistical software is not necessary for analyzing timeseries data, suggesting that standard software packages like R or S or SPLUS (https://link.springer.com/book/10.1007/b98882) could be used to perform these analyses instead.

My understanding of the challenges in statistical analysis of timeseries data is that a key feature is to account for the statistical dependency structure of timeseries data. This needs to be estimated based on the smoothness of the dataset, and is done applying random field theory (RFT) to estimate the number of independent measurements (resolution elements) truly present in the timeseries. My understanding is that RFT-corrections are not built in into R or other packages, thus requiring one to either develop their own code for RFT corrections, or to use spm1D.

However, I am just a user of these techniques, not a developer. Can anyone point out to whether my understanding of what is possible with spm1d vs standard statistical analysis packages is correct? 

Just to make an example, could a 1-way ANOVA that uses timeseries data be conducted using a standard linear mixed model with 1 fixed effect and one random effect to account for the repeated measures? In that case, what options would there be to correct for the many (like ~100, but not all independent given the smoothness of the data) levels for the repeated factor?

**Comment by 0todd0000** [comment]
> My understanding is that RFT-corrections are not built in into R or other packages, thus requiring one to either develop their own code for RFT corrections, or to use spm1D.

This is correct for practical purposes. RFT corrections are available in a variety of software packages including, for example, the [fmri package for R](https://cran.r-project.org/web/packages/fmri/fmri.pdf), but these are not easy to use for 1D data analysis.

> I have had reviewers point out to the fact that a dedicated statistical software is not necessary for analyzing timeseries data, suggesting that standard software packages like R or S or SPLUS.

The reviewers are indeed correct that a broad range of time series data analysis possibilities are supported in many software packages, including R and SAS. However, I would challenge the reviewers by asking them what function(s) in those packages can be used to conduct classical hypothesis testing on whole 1D curves (i.e., t tests, regression, ANOVA, etc. at the whole-curve level). I expect that they will not be able to answer that question because standard time series analysis functionality does not support classical hypothesis testing. **spm1d** and other SPM packages fill that void.

One challenge in dealing with reviewers is that many researchers, including statisticians, are unaware of RFT, and/or how and why it can be used to test hypotheses regarding 1D (and nD) data. In response to reviewers' concerns, I would cite the literature, where [tens-of-thousands of papers](https://spm1d.org/References.html) use RFT, all with SPM/RFT packages that are not part of any standard statistics software release. If you think the reviewer is a statistician, I would recommend citing Liebl & Reimherr (2019), which describes RFT in the context of statisticians' historical perspectives on time series data, including RFT's unique mathematical properties and why RFT can indeed be used for robust hypothesis testing (provided of course that the data adhere RFT's assumptions, like normality). 

Liebl D, Reimherr M. Fast and Fair Simultaneous Confidence Bands for Functional Parameters. arXiv preprint arXiv:1910.00131. 2019 Sep 30. https://arxiv.org/abs/1910.00131


> Just to make an example, could a 1-way ANOVA that uses timeseries data be conducted using a standard linear mixed model with 1 fixed effect and one random effect to account for the repeated measures? In that case, what options would there be to correct for the many (like ~100, but not all independent given the smoothness of the data) levels for the repeated factor?

This is a good example, and I would pose this question to the reviewer(s). No standard package in R or SAS could do this. The [fda package for R](https://cran.r-project.org/web/packages/fda/fda.pdf) could partly handle this, but it uses a nonparametric permutation approach to hypothesis testing. RFT provides the equivalent parametric solution.
