### ISSUE TITLE
Matching p-values to points\clusters in 3D plot

### ISSUE THREAD

**Issue by Little-Foot-Shapes** [0todd0000/spm1d#154]
Hello Todd, 

I am performing ANOVA, regression and post-hoc independent t-tests on 3D foot scan data. I have all the results and I can plot the F\t maps (using colormap) on the 3D surface, however, I would like to also plot the p-values for the clusters on the 3D surface using colormap.
I cannot seem to find a way to match the p-values of the clusters to points. My data is 148*22498 with groups within this for ANOVA and post-hoc. I know that xy in snpmi is the location of the centre of the cluster and that the code snpmi.plot(); snpmi.plot_threshold_label(); snpmi.plot_p_values();  does this in a 2D plot, but how do I relate the p-values to the list of points so I can plot them in 3D? 
Thank you.

Best Regards
Mat

**Comment by 0todd0000** [comment]
Hi Mat,

This is not possible in **spm1d**, and as emphasized in [this 2D post](https://spm1d.org/doc/Stats2D/ex2d.html), **spm1d** "does not provide cluster-specific p values" for nD data.  **Please ignore all p values for nD data** (where n > 1). In **spm1d**, only the critical threshold (and only from non-parametricc inference) is an appropriate probabilistic quantity for nD analysis. 

To solve this problem, and to calculate nD cluster probabilities, you'd need to use an SPM software package that supports nD data analysis, like SPM12 or NiPy.

Todd

**Comment by Little-Foot-Shapes** [comment]
Hi Todd, 

Thank you!

Mat
