### ISSUE TITLE
Format Of XLSX file

### ISSUE THREAD

**Issue by Shivangi2208** [0todd0000/spm1d#156]
Hello,
is there a format required for excel files to be used for spm1d. I have an excel sheet with first row representing Knee angle and the next three rows Muscle Moment Arms. I wanted to perform a t-test between the Moment arms for each value of Knee Angle. However when I plot spm I get column numbers as my x axis and not the values of Knee angle. Kindly help.

Regards,
Shivangi

**Comment by 0todd0000** [comment]
Hello Shivangi,

The data you have described may not be suitable for analysis using **spm1d**. For **spm1d** analysis, data arrays must have one of the following two forms:

* ( J x Q )   --- a 2D array containing [univariate 1D data
* ( J X Q X I )  --- a 3D array containing multivariate 1D data

where:

* J = sample size (number of 1D observations)
* Q = domain size (usually number of time nodes)
* I = number of variables (e.g. number of vector components)

The data you described are not really of this form. One problem is that there are only three rows of moment arms, implying three 1D observations. Three observations are insufficient for t tests.

Todd

**Comment by Shivangi2208** [comment]
Thank you, Todd. I will format it accordingly.

Regards,
Shivangi
