### ISSUE TITLE
how to apply cop on the registered foot pressure pictures

### ISSUE THREAD

**Issue by maryampol** [0todd0000/spm1d#158]
Hi Pataky,
I'm working on a project about cop trajectory differences between fallers and non-fallers older adults. I have some question regarding your valuable experience in the "Age-related plantar center of pressure trajectory changes during barefoot walking" project:

1-after registering the pressure picture, how did you apply the cop trajectory on the new normalized picture? I would be thankful if you send me your code in this part.
2-what was your coordinated axis for medial/lateral, ant/post displacement of COP? for example in other cop geometry papers, med/lat reference line was the foot axis(the line from heel to mt2).

I'm looking forward to hearing from you in near future.
The best,

**Comment by 0todd0000** [comment]
Hello,

> 1-after registering the pressure picture, how did you apply the cop trajectory on the new normalized picture? I would be thankful if you send me your code in this part.

The COP trajectory was calculated **after** registration. When calculating the COP trajectory after registration like this, you do not need to apply any transformations to the extracted COP trajectories. If you have already have code to extract the COP trajectory, then I think perhaps you do not require additional code?

> 2-what was your coordinated axis for medial/lateral, ant/post displacement of COP? for example in other cop geometry papers, med/lat reference line was the foot axis(the line from heel to mt2).

The principal axes of the mean foot (i.e., the mean of all registered feet) were used to define the coordinate system.

Todd

**Comment by maryampol** [comment]
I am sorry to have caused you any trouble. many thanks for your kind reply.
unfortunately, I didn't understand, here I have attached one of our extracted data from the NOVEL LE pressure plate that give us the cop x and y in addition to the maximum pressure picture.
1- as the cop is extracted at the same time with the pressure picture, after image normalization and registration what should we do with the cop x and y?
2- I have some codes for the image registration(attache file received from Gisela) and I'm so confused about what should I do with the cop after image registration regarding our equipment(novel pressure plate).
3-would you please explain to me what did you mean by: "the principal axes of the mean foot "
in your paper, you mention the older adult shifted the COP more laterally than the young in the forefoot, from which reference line you calculate this shift? I mean that in your graph the zero lines represent for what?



[pressure from novel.xlsx](https://github.com/0todd0000/spm1d/files/5873787/pressure.from.novel.xlsx)
[agepp.zip](https://github.com/0todd0000/spm1d/files/5873791/agepp.zip)

**Comment by 0todd0000** [comment]
Please note:

1. I have deleted the files. One of the files (containing Matlab code) is not meant for public sharing;  please keep this file's content confidential.  The other file (containing Novel data) may also be unsuitable for public sharing, so I have deleted this file as a precaution;  please ask your laboratory manager to confirm whether the data are publicly shareable.

2. This forum is limited to **spm1d** code and related issues, so please understand that issues beyond **spm1d** cannot be supported in this forum. Although **spm1d** can indeed be used to analyze plantar pressure PP data as described [here (Python)](https://spm1d.org/doc/Stats2D/ex2d.html) and [here (Matlab)](https://spm1d.org/doc/Stats2D/ex2d_matlab.html), it can not be used for general PP data processing steps including for example: registration and COP calculation.

Regarding your specific questions:

> 1- as the cop is extracted at the same time with the pressure picture, after image normalization and registration what should we do with the cop x and y?

To calculate the COP trajectory yourself you would need to calculate the COP location for each data frame, using an approach like [this](https://learnopencv.com/find-center-of-blob-centroid-using-opencv-cpp-python/). 

> 2- I have some codes for the image registration(attache file received from Gisela) and I'm so confused about what should I do with the cop after image registration regarding our equipment(novel pressure plate).

This code supports RSScan data but not Novel data. Separate code would need to be written to support Novel data.

> 3-would you please explain to me what did you mean by: "the principal axes of the mean foot "

The [principal axes](https://en.wikipedia.org/wiki/Moment_of_inertia#Principal_axes) of the foot are the eigenvectors of a PP image's covariance matrix, and can be calculated as described [here](https://alyssaq.github.io/2015/computing-the-axes-or-orientation-of-a-blob/), for example.

**Comment by maryampol** [comment]
Dear proffesor,Many thanks for your kind responses.I apologizes for all my mistake regarding the file attacments.
I know you are alot busy and Gisela talked with you about my project before, but I would like to know if there is any possibility for you to be as an advisor in this part of my thesis ? As I have O & P on my backgroung these mathematical issues are very confusing in data processing for me. 
Please let me know if you can join our team.
Best wishes,----
Fateme PolPh.D. Student
Department of Orthotics and Prosthetics 
School of Rehabilitation Sciences
Isfahan University of Medical Sciences

 

    On Wednesday, January 27, 2021, 05:09:40 AM GMT+3:30, Todd Pataky <notifications@github.com> wrote:  
 
 


Please note:
   
   -    
I have deleted the files. One of the files (containing Matlab code) is not meant for public sharing; please keep this file's content confidential. The other file (containing Novel data) may also be unsuitable for public sharing, so I have deleted this file as a precaution; please ask your laboratory manager to confirm whether the data are publicly shareable.

   -    
This forum is limited to spm1d code and related issues, so please understand that issues beyond spm1d cannot be supported in this forum. Although spm1d can indeed be used to analyze plantar pressure PP data as described here (Python) and here (Matlab), it can not be used for general PP data processing steps including for example: registration and COP calculation.


Regarding your specific questions:


1- as the cop is extracted at the same time with the pressure picture, after image normalization and registration what should we do with the cop x and y?


To calculate the COP trajectory yourself you would need to calculate the COP location for each data frame, using an approach like this.


2- I have some codes for the image registration(attache file received from Gisela) and I'm so confused about what should I do with the cop after image registration regarding our equipment(novel pressure plate).


This code supports RSScan data but not Novel data. Separate code would need to be written to support Novel data.


3-would you please explain to me what did you mean by: "the principal axes of the mean foot "


The principal axes of the foot are the eigenvectors of a PP image's covariance matrix, and can be calculated as described here, for example.

**Comment by 0todd0000** [comment]
(Issue closed because the topic is not directly related to spm1d.)
(All matters discussed with user maryampol in an external conversation.)
