### ISSUE TITLE
anova2rm 

### ISSUE THREAD

**Issue by PaoloBrasi** [0todd0000/spm1d#165]
Hello Todd, 
I have a question regarding which is the most appropriate test between anva2rm, anova2onerm and anova2tworm. 
I'll explain the experimental set up. 
I have 14 subjects which underwnt instrumented (stereophotogrammetry) gait analysis in two conditions: walking barefoot (C1) and walking while wearing an orthosis (C2). Kinematics was estimated using 3 different 3D models to reconstruct body segemnts (M1, M2 and M3).  I am using the most representiative trial for each subject, so I have the same number of trials for each condition and model. 
I am interested in verifying if there are differences between the three models in each condition and i would like to understand how much these differences may be affected by the conditions. 
I have to main questions: 
Which is the most appropriate test to be used in this case?
How the variables should be organized? ( I am using matlab) 

Thank you in advance and kind regards, 

Paolo.

**Comment by 0todd0000** [comment]
Hi Paolo,

For deciding between the ANOVA designs you just need to know the conditions in which each subject performed. If a given subject performed in all conditions, then the appropriate design is **anova2rm**.  If a given subject performed in multiple but not all conditions the design is likely **anova2onerm**.  (There shouldn't be an **anova2tworm** design; there is only an **anova3tworm** for a three-way ANOVA with two RM factors.)

In this case it sounds like **anova2rm** is appropriate. An example of a case where **anova2onerm** would be appropriate is two populations (e.g. patients and controls) and two conditions (e.g. shod and barefoot);  in this case a specific individual can't both be a patient and a control.

> How the variables should be organized? ( I am using matlab)

You need:
- `y` = data;  a (J, Q) array where J is the number of observations and Q is the number of time nodes
- `A` = Factor A levels (e.g. barefoot=1, orthosis=2);  a (J,1) array
- `B` = Factor B levels (e.g. M1=1, M2=2, M3=3);  a (J,1) array
- `S` = Subject integer labels;  a (J,1) array

The example script: `./spm1dmatlab/examples/stats1d/ex1d_anova2rm.m` shows a few examples of how the data should be set up.

Todd

**Comment by PaoloBrasi** [comment]
Many thanks for the fast and clear answer. 

Paolo
