### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by PaigeRice90** [0todd0000/spm1d#166]
Hello! I am trying to download the spm1d package for python, however, this pops up in my shell, and I'm not familiar with the verbage or how to address this issue. Any suggestions would be helpful to try and fix this! Thank you!

<img width="568" alt="Screen Shot 2021-04-22 at 9 44 03 AM" src="https://user-images.githubusercontent.com/83016808/115724851-4f1d5b80-a34f-11eb-8370-062688b6918e.png">

**Comment by 0todd0000** [comment]
Hello,

This error implies that you have insufficient privileges on that computer to install software using easy_install.

Regardless, please note **spm1d** no longer officially supports Python 2.X. If you're willing to try Python 3 I'd suggest:

- Install the Python 3 version of [Anaconda](https://www.anaconda.com/products/individual)
- Try one of these:
    - Try `easy_install` again
    - Use the [anaconda installation command](https://anaconda.org/conda-forge/spm1d) 
    - Download the source code and run `python setup.py install`
