### ISSUE TITLE
Interpretation of SPM two-tailed inference

### ISSUE THREAD

**Issue by Thomas76000** [0todd0000/spm1d#167]
Hello Todd, 

I am starting to use the SPM and I have a question about the interpretation of the two-tailed inference. 
I am currently doing a study on the influence that jerking may have on the risk of ankle sprains. 
To do this I am conducting a gait study and comparing data on jerk variations in a group with ankle instability and a control group. 
My hypothesis is that subjects suffering from ankle instability will present greater variations in jerk than the control group (without pathology) 

Here is an example of the result I obtain for the variations of the jerk in a sagittal plane (flexion-extension of the foot) following a t-test (paired t-test) (X axis = % gait cycle, Y axis = Jerk value m.s-3)

Despite reading several topics or articles, I admit that my understanding of the test results remains unclear  
My question is about the interpretation of exceeding the positive or negative threshold. 

Is there a difference in the interpretation of a positive or negative threshold crossing? 
Each time the threshold is reached, does this mean that the unstable group obtains greater jerk variation than the control group? 
 
![untitled](https://user-images.githubusercontent.com/83072739/115871678-26758e80-a441-11eb-94c7-6dcf2cfc1f1f.jpeg)

Thank you in advance for the time you will take to answer my question

**Comment by 0todd0000** [comment]
Hello, I noticed that the issue is now closed. Just in case this was an accident:

<br>
<br>

> Is there a difference in the interpretation of a positive or negative threshold crossing?

No, in both cases t values that large are expected to occur relatively infrequently if there is truly no effect.

<br>
<br>

> Each time the threshold is reached, does this mean that the unstable group obtains greater jerk variation than the control group?

The  t value is conceptually `(meanA - meanB) / variance` , so is positive when meanA is greater than meanB, and vice versa.
