### ISSUE TITLE
Post-hocs two-way RM anova on 1 factor

### ISSUE THREAD

**Issue by aurelienPatoz** [0todd0000/spm1d#172]
Dear Sir, 

We have conducted a two-way (group x insole) RM anova using spm1d in python as

spm1d.stats.anova2onerm(data, groups_factor, insoles_factor, subjects, equal_var = True)

We have 2 groups, 3 different insoles, and 115 subjects.

Statistically significant group effect, insole effect, and interaction effect were reported.

Here is the insole effect:
[spm_force_Y_insole-effect.pdf](https://github.com/0todd0000/spm1d/files/6452552/spm_force_Y_insole-effect.pdf)

However, when I conduct the post-hoc analysis for the insole effect using

t = spm1d.stats.ttest2(data1, data2, equal_var = True)

and perform the inference with 

t.inference(alpha = p_critical, two_tailed = True))

I do not get any significant difference.

Here are the 3 figures:
[spm_force_Y_no-group_11_hard-11_post-hoc.pdf](https://github.com/0todd0000/spm1d/files/6452554/spm_force_Y_no-group_11_hard-11_post-hoc.pdf)
[spm_force_Y_no-group_11_soft-11_post-hoc.pdf](https://github.com/0todd0000/spm1d/files/6452555/spm_force_Y_no-group_11_soft-11_post-hoc.pdf)
[spm_force_Y_no-group_soft-11_hard-11_post-hoc.pdf](https://github.com/0todd0000/spm1d/files/6452556/spm_force_Y_no-group_soft-11_hard-11_post-hoc.pdf)

Note that I have set p_critical using Bonferroni corrections assuming 3 post-hoc tests (because I have 3 conditions and I don't need to use the group appartenence when I am looking at the insole effect).

In addition, we have very small visible differences between our insoles as it can be noticed on this figure:
[force_y_no-group.pdf](https://github.com/0todd0000/spm1d/files/6452560/force_y_no-group.pdf)

Do we get a significant insole effect because of the very high number of participants?

Could you please let us know if there are any mistakes in our analysis and could you please help us with the understanding of our results?

Best regards,
Aurélien

**Comment by aurelienPatoz** [comment]
Thank you very much for having pointed the mistake.
I have corrected my notebook and now it reflects the results of the anova.

Moreover, plotting the paired differences is also more reflecting of the post hoc results.

Best regards,
Aurélien

**Comment by 0todd0000** [comment]
Great!  I'll close this issue now, but please feel free to re-open it or submit a new issue if needed.
