### ISSUE TITLE
Bilateral Comparisons

### ISSUE THREAD

**Issue by nmartonick** [0todd0000/spm1d#177]
Hello Todd,

Problem:
Using the spm1d MATLAB code, I have been able to graphically represent and compare dominate and non-dominate limbs during a single leg drop-landing from 1 group. However, I am struggling to conceptualize a way to compare bilateral differences between groups with continuous data. Researchers have previously taken the average difference of the two variables (knee flexion for example) at each timeframe from 0-40ms and compared that difference between males and females. While in a way this still incorporates time, it is still a discrete analysis (each participant is given a single value for their bilateral difference). I believe the primary problem is that there is not a trace/waveform for the bilateral difference. 
Question:
Is there a way to use SPM to compare the differences between two waveforms to the differences between two other waveforms? 

Thank you and your team for putting together this package. Analyzing biomechanical data with these concepts/graphs has been a lot of fun and makes a lot more sense to me as well. 

Nick

**Comment by 0todd0000** [comment]
Thank you for the feedback!

Yes, this can be done using two-way repeated-measures (RM) ANOVA, with one repeated-measures factor. In **spm1d** the function name is **spm1d.stats.anova2onerm**.  In this case the RM factor is LIMB (left or right) and the other factor is GENDER.

Alternatively, if it would be sufficient to just consider means, then you could calculate within-subject means separately each limb, then calculate the limb difference for each subject, then finally submit these differences to a two-sample t test. The result should be the same as the ANOVA result above.

**Comment by nmartonick** [comment]
Ok. I looked at the example data and this makes sense.
