### ISSUE TITLE
Issue with SPM plot in Matlab

### ISSUE THREAD

**Issue by greentable4** [0todd0000/spm1d#178]
Hi,

I am trying to use the SPM package in Matlab to perform a one-way ANOVA. Each variable is composed of one column with one row. For example:

6.8
7
6
6.4
6
4.5
4
etc.

This is the script I am using in Matlab:

F=spm1d.stats.anova1(variableA,variableB,variableC);
Fi=F.inference(0.05)
Fi.plot()

However, I get the following error:

Error in script_SPM (line 3)
Fi.plot()

I have also tried to use the two scripts for the one-way ANOVA in the following documentation: https://spm1d.org/doc/Stats1D/anova.html#one-way-anova

However, I still can't plot. What could be the error?

Thank you.

**Comment by 0todd0000** [comment]
The function call for **anova1** looks like this in MATLAB:

```octave
F  = spm1d.stats.anova1(y, A);
```

where:

* *y* = data array
* *A* = vector of integer group labels

If your three variables are named *v1*, *v2* and *v3*, you should be able to solve the problem like this:

```octave
y = [v1; v2; v3];
A = [ 1 * ones( size(v1, 1) );    2 * ones( size(v2, 1) );     3 * ones( size(v3, 1) );  ]

F  = spm1d.stats.anova1(y, A);
```
