### ISSUE TITLE
Three way repeated measures ANOVA 1D SPM and vector field.

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#18]
Hi Todd,

From the website, the available three way rmANOVA (below), does not allow complete three way analysis?
-Three-way ANOVA
-Three-way nested ANOVA
-Three-way ANOVA with repeated-measures on two factors
-Three-way ANOVA with repeated-measures on one factor

Can I say that there is no function as yet in spm1d that can perform vector field analysis using >= 2 repeated measures?

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
That is correct, only one-way multivariate analyses are currently supported (**spm1d.stats.manova1**). All currently-supported multivariate procedures are listed here:
http://www.spm1d.org/NewFeatures.html#multivariate-analysis

Note that there are also many standard ANOVA / MANOVA features that are not yet implemented including:
* unbalanced designs
* missing data
* non-sphericity corrections for repeated-measures designs and for multivariate procedures
* post hoc analyses (other than Bonferroni)

Until these features are implemented and thoroughly tested **spm1d** will have a **0.x** version number.

Best,
Todd

**Comment by bernard-liew** [comment]
Thanks Todd,

I am doing 2way repeated measures. I have significance each factor and its interaction. The immediate post-hoc is performing multiple paired t-test, and I recognize the limitations stated in the documentation.

What is the recommended code for doing multiple paired t test on the data frame I used for the initial 
rm analysis? That is because every row corresponds to a different repeated measure.

Many thanks Todd. 

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

There is no recommended code because at this stage we haven't been able to either code or test all post hoc situations which can arise in ANOVA. Moreover, we don't intend to fully automate post hoc analyses (like SPSS and other software does) because post hoc analyses simply qualify the main ANOVA results.

For your situation in which there is an interaction, it is difficult to make strong conclusions regarding the main effects, so I'd focus post hoc analyses on describing the interaction effect, which can be done sufficiently with (i) the interaction F statistic and (ii) within- / between-subject means as appropriate to your design.

Cheers,

Todd

**Comment by bernard-liew** [comment]
Thanks Todd,

I am actually asking more about dataframe manipulation for post-hoc testing, rather than the test per se. In cases of null interaction, and I want to doing paired t-test to identify where the significance arrives from, the typical paired t-test code is

t  = spm1d.stats.ttest_paired(Y0, Y1)

This necessitates me creating another dataframe (different from the one I used for anova2rm). In fact, it necessitates creating various dataframes based on the intended pairwise comparisons I have to make. Am I right? Is there an efficient way to do it?

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
Apologies for misunderstanding.  That's correct, the analyses are not automated so you need to create new variables. One way to do this is to use binary indexing:

```
YA1 = Y[A==1]
YA2 = Y[A==2]
YA3 = Y[A==3]
```

or

```
YA1,YA2,YA3 = [Y[A==i]  for i in [1,2,3]] 
```

or you could automate indexing for an arbitrary number of levels like this:

```
YY = [Y[A==i]  for i in np.unique(A)] 
```


Todd
