### ISSUE TITLE
Error when conducting non-parametric t-test

### ISSUE THREAD

**Issue by EmblaJ** [0todd0000/spm1d#181]
Hi,

Sometimes I have a problem when conducting a non-parametric t-test in spm (sometimes I don't have this problem). A screen shot of the error is attached. 
<img width="835" alt="error_snpm" src="https://user-images.githubusercontent.com/88278895/127773759-1f57af7a-2793-4c80-b933-e4969e4ca2ab.png">

Can I fix this somehow?

Thank you in advance!

**Comment by 0todd0000** [comment]
That error can arise if there are no supra-threhold clusters. To fix the error, check whether supra-clusters exist when attempting to access cluster details, like this:

```python
if len( snpmi.clusters ) > 0:
    cluster = snpmi.clusters[0]
```

Equivalently, you can instead check whether the null hypothesis is rejected, like this:

```python
if snpmi.h0reject:
    cluster = snpmi.clusters[0]
```

**Comment by EmblaJ** [comment]
Thanks.

And what do I do when this comes up?

<img width="714" alt="Snpm_Cluster_2" src="https://user-images.githubusercontent.com/88278895/129106509-808ad800-2696-4936-a6ab-01183a28a1f5.png">

**Comment by 0todd0000** [comment]
Try moving the `print` statement into the `if` statement like this:

```python
if len( snpmi.clusters ) > 0:
    cluster = snpmi.clusters[0]
    print( cluster )
```

**Comment by EmblaJ** [comment]
Great, it works now.
Thank you!
