### ISSUE TITLE
Spm1d.stats.glm, LinAlgError: Singular matrix

### ISSUE THREAD

**Issue by EmblaJ** [0todd0000/spm1d#185]
Hi.
I am doing multiple regression analyses using spm1d glm.
Can I do something to prevent this error, LinAlgError: Singular matrix?

<img width="741" alt="LinAlgError_Singular matrix" src="https://user-images.githubusercontent.com/88278895/129488888-d9afa4ef-985e-4c29-96a7-e91a0045bc54.png">

**Comment by 0todd0000** [comment]
Hello, sorry for the very long delay!!

This error occurs if two columns of the design matrix `X` are the same.  The columns must be linearly independent.
