### ISSUE TITLE
Aacceess x-y coordinates of alpha values

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#186]
Hi Todd,

This is not a problem.

I want to access the x-y coordinates of the SPM plots, to custom plot in other software.

The y is easy, that is the spm.z function.
Is the x, automatically 1: length of vector?

The reason I ask is, if that is the case, what is the function used to shade the cluster? if the x values are integers but the stand and end points of a cluster are floats, the cluster area will not be nicely shaded.

Many thanks for helping.

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

The easiest way to do this is with Matplotlib's [`fill_between`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.fill_between.html#examples-using-matplotlib-pyplot-fill-between) function. Here is a quick script based on the [one-sample t example](https://github.com/0todd0000/spm1d/blob/master/spm1d/examples/stats1d/ex_ttest.py):


```python
import numpy as np
from matplotlib import pyplot as plt
import spm1d

dataset    = spm1d.data.uv1d.t1.SimulatedPataky2015b()
y,mu       = dataset.get_data()

alpha      = 0.05
t          = spm1d.stats.ttest(y, mu)
ti         = t.inference(alpha, two_tailed=False, interp=True, circular=False)

Q          = y.shape[1]
x          = np.linspace( 0, 1, Q )
z          = ti.z
zc         = ti.zstar * np.ones( Q )

plt.close('all')
plt.figure( figsize=(8,6) )
ax = plt.axes()
ax.plot(x, z)
ax.plot(x, zc, ':' )
ax.fill_between(x, z, zc, where=(z>zc), interpolate=True )
plt.show()

```

<br>
<br>
This produces the figure below.

Note that `interpolation` should be set to `True` to avoid the problem you mention:  setting this to `False` makes the clusters' endpoints line up with `x` nodes.

**spm1d** similarly interprets between `x` nodes to get the cluster endpoints. If you're interested in the details you can find them in the `plot_cluster_patches` on Line 213 in the current version of [_plot.py]( https://github.com/0todd0000/spm1d/blob/master/spm1d/_plot.py).

<br>
<br>

![fig](https://user-images.githubusercontent.com/4276626/130193029-4c669fb1-9498-40f1-8b46-4428c389f609.png)

**Comment by bernard-liew** [comment]
Thank you Todd for your prompt reply. That is really useful.
