### ISSUE TITLE
Stats results different based on order loaded into model

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#19]
Hi Todd,

When performing a two way repeated measures SPM anova 1d, I realised that

1) FF        = spm1d.stats.anova2rm(Y, B, A, SUBJ,equal_var=True)
2) FF        = spm1d.stats.anova2rm(Y, A, B, SUBJ,equal_var=True)

gives different results.Does this have to do with the type of sum of squares usually explained in 0d ANOVA? 

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

Only Type III sum-of-squares is used, and the results should be the same for "A, B" and "B, A", but ordered differently.

That is, if you order the factors as:  "A, B", then the results will be ordered:  "FA, FB, FAB".
But if you order the factors as:  "B, A", then the results will be ordered:  "FB, FA, FAB".

If that does not solve the problem, then please send a rendering of the design matrix:
```
design    = spm1d.stats.anova.designs.ANOVA2rm(A, B, SUBJ)
design.plot()
```

Todd

**Comment by bernard-liew** [comment]
![y equal ba design matrix](https://cloud.githubusercontent.com/assets/12288089/8795374/36d5c88c-2fbf-11e5-9340-29f908a31b55.png)
![y equal ba](https://cloud.githubusercontent.com/assets/12288089/8795376/36d6946a-2fbf-11e5-80d7-730e9f1d09d6.png)
![y equal ab design matrix](https://cloud.githubusercontent.com/assets/12288089/8795377/36d9beba-2fbf-11e5-8499-d13ab6ec5ebe.png)
![Uploading Y equal AB.png…]()

Hello Todd,

attached is the spm results (thought I may just send anyway) and design matrix.

Regards,
Bernard

**Comment by bernard-liew** [comment]
![y equal ab](https://cloud.githubusercontent.com/assets/12288089/8795422/8637077e-2fbf-11e5-8929-7756fbf7718f.png)

Forgot this spm figure...

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
The design looks somewhat more complex than the designs in the examples, so I think I'll need to see the A, B and SUBJ values.  Could you please either paste them into your reply or send them to me by email?
Todd

**Comment by 0todd0000** [comment]
Hi again,
The factors (A, B and SUBJ) look fine, and I've found the problem:
The code has been tested for 2 x K designs but not 3 x K designs, and for the latter there appears to be a minor bug when the design matrix is formed. I've found a quick fix for this particular 3 x 3 dataset, but please give me a few days to test the new code out on some published (3 x K) results.
Todd

**Comment by bernard-liew** [comment]
Many thanks Todd for the help... :)

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
I'm struggling to find 3xK ANOVA examples published on the internet.  Please give me a few more days to generate some example data and to verify the spm1d results.
Apologies for the delay,
Todd

**Comment by bernard-liew** [comment]
Hi Todd,

Understand the time, don't worry....

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi again Bernard,
I've been exploring the bug but haven't yet been able to find a good solution. It seems that 3x3 and 4x4 designs are affected and that 3x4, 3x5 and 4x5 designs are OK.  It will take some more time to find a stable solution, please give me another week or two.
In the meantime, would you like a quick fix that will work for your dataset?  There's a very minor edit you can make to the source code that will solve the problem for this particular 3x3 design, but unfortunately might cause problems for other designs.
Todd

**Comment by bernard-liew** [comment]
Hello Todd,

Very grateful for the help. A quick fix for me is good for now. 

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
The latest **spm1d** version (uploaded to github yesterday) should work, please give it a try.  For the dataset you sent the latest version yields the results depicted in the figure below.  The top row of panels depicts the results of:
```
FA,FB,FAB = spm1d.stats.anova2rm(Y, A, B, SUBJ, equal_var=True)
```
and the bottom row depicts the results after swapping the A and B factors:
```
FB,FA,FAB = spm1d.stats.anova2rm(Y, B, A, SUBJ, equal_var=True)
```

Please be aware that this fix does not work for arbitrary (3 x K) or (4 x K) designs.  I'll write again once a more stable fix is available.

Sorry for this bug, and thanks again very much for pointing it out!

Todd

![fig](https://cloud.githubusercontent.com/assets/4276626/8899924/53fbadea-3475-11e5-8f65-638392f8e33f.png)

**Comment by bernard-liew** [comment]
Many thanks Todd,

I guess it is part and parcel of creating programs... Not a problem.

Can I say that print spm1d.__version__0.3.0.1 (2015/07/09)?? I tried pip uninstall spm1d and easy_install spm1d... The version after this is 0.3.0.1 (2015/07/09). I got a feeling I haven't successfully updated it as running 2way RM causes the same problem.

should I easy_install spm1d==____??

Many thanks Todd,


Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
Sorry for the confusion.  It's not an official update, so I didn't make it available through pypi (i.e. easy_install and pip). Please download the source code manually from github, unzip, open a terminal, navigate to the folder containing setup.py then run:
```
python setup.py install
```
from the terminal.  That will do the same thing as easy_install, and should overwrite the existing version of **spm1d**.
Todd

**Comment by bernard-liew** [comment]
Thanks Todd,

Yes installing from the terminal seems to run, but I must say I do not see the original files being in spm1d being updated (ie date modified remained the same). 

I have reproduced the the individual effect curves, but not the interaction curves. I assume the fact that no shaded regions are present due to it being a temporary fix? Because I could print the inference clusters. 

![fa fb fab](https://cloud.githubusercontent.com/assets/12288089/8924477/c59d48a8-3530-11e5-818d-ca4b845cf45c.png)
![fb fa fab](https://cloud.githubusercontent.com/assets/12288089/8924478/c59ddafc-3530-11e5-9ce3-a23e0afcc77c.png)


Another notice: When I ran the old anova2RM code on another dataset, laid out in same format, albeit on a subset of the original population, this came up...

C:\Users\14342453\AppData\Local\Enthought\Canopy\User\lib\site-packages\spm1d\stats\anova\solvers.py:117: RuntimeWarning: divide by zero encountered in divide
  MS,MSE        = (SS/df), (SSE/dfE)
C:\Users\14342453\AppData\Local\Enthought\Canopy\User\lib\site-packages\scipy\stats\_distn_infrastructure.py:767: RuntimeWarning: invalid value encountered in greater
  cond = logical_and(cond, (asarray(arg) > 0))
C:\Users\14342453\AppData\Local\Enthought\Canopy\User\lib\site-packages\rft1d\prob.py:69: RuntimeWarning: invalid value encountered in double_scalars
  p         = Q * (p**n)
C:\Users\14342453\AppData\Local\Enthought\Canopy\User\lib\site-packages\rft1d\prob.py:352: RuntimeWarning: invalid value encountered in double_scalars
  fn    = lambda x : (rft(1, 0, STAT, x[0], df, resels, n, Q, False, version)[0] - aaa)**2
C:\Users\14342453\AppData\Local\Enthought\Canopy\User\lib\site-packages\scipy\optimize\optimize.py:460: RuntimeWarning: invalid value encountered in absolute
  if (numpy.max(numpy.ravel(numpy.abs(sim[1:] - sim[0]))) <= xtol and
C:\Users\14342453\AppData\Local\Enthought\Canopy\User\lib\site-packages\rft1d\geom.py:475: RuntimeWarning: invalid value encountered in greater_equal
  L,n         = bwlabel(y >= u, merge_wrapped=wrap)

Not sure what is different? 

Many thanks Todd
Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
I'll open a new issue for the other dataset then write again with a response to the first issue.
Todd

**Comment by 0todd0000** [comment]
Hi Bernard,

> "Yes installing from the terminal seems to run, but I must say I do not see the original files being in spm1d being updated (ie date modified remained the same)."

Please first uninstall **spm1d** by deleting the folder:
C:\Users\USERNAME\AppData\Local\Enthought\Canopy\User\lib\site-packages\spm1d
Then verify successful uninstall by re-launching Canopy and typing
```import spm1d```
That should produce the following error:
```ImportError: No module named spm1d```
Then install the new version by running
```python setup.py install```
from a Command Prompt.


> "I have reproduced the the individual effect curves, but not the interaction curves. I assume the fact that no shaded regions are present due to it being a temporary fix? Because I could print the inference clusters."

Are you plotting the test statistic results or inference results?
Since critical thresholds are not depicted in the figures above I'd guess that this is just the raw pre-inference test statistic.

Todd

**Comment by 0todd0000** [comment]
With the current version of **spm1d** the following commands produce the figure below. The threshold and shaded regions are depicted.

```
FA,FB,FAB    = spm1d.stats.anova2rm(Y, A, B, SUBJ, equal_var=True)
FAi = FA.inference(0.05)
FAi.plot()
```

![fig](https://cloud.githubusercontent.com/assets/4276626/8927668/10ebf1ba-3554-11e5-809d-06d31f453168.png)

**Comment by 0todd0000** [comment]
Hi Bernard,

Apologies for the delay!

The new version of the code is ready (version 0.3.1) both at GitHub and at PyPi.

You should now be able to swap the order of the factors in **spm1d.stats.anova2rm** and obtain identical results.  

I'll close this issue for now because it pertains to the previous version (0.3.0.1).  If you encounter any new problems please let me know by creating a new issue.

Cheers,

Todd
