### ISSUE TITLE
GLM model assumption of normality

### ISSUE THREAD

**Issue by eleonora-mont** [0todd0000/spm1d#190]
Hi Todd,

I just run a normality test on my pressure data and this is what it looks like
![normality_test_39participants](https://user-images.githubusercontent.com/79143162/133765591-103c27fb-4e55-4562-81b8-cbf75a334de9.jpg)

The data is overall normally distributed although in some points as you can see, data crossed the threshold. Do you think it would be ok to use the GLM model on the present data? My concern is that it violetes the assumption of normality for the GLM model, although in few points. 

Thanks,

Eleonora

**Comment by 0todd0000** [comment]
Hi Eleonora,

Are these 2D data?  If yes, then only nonparametric analysis is possible in **spm1d**. It is fine to run these analyses (GLM or otherwise) because nonparametric procedures do not assume normality.

Todd

**Comment by eleonora-mont** [comment]
Hi Todd,

Thanks for your reply. Yes, this is 2D plantar pressure data. I thought that only parametric GLM procedure was available in spm1d, is this incorrect? That is why I run normality test to check on pressure data for it. 

Thanks,
Eleonora

**Comment by 0todd0000** [comment]
Yes, the GLM procedure is currently available only for parametric inference.

However, as discussed in #183, only nonparametric inference can be used for 2D analysis in **spm1d**. Thus there is no need to check normality for 2D analysis.

**Comment by eleonora-mont** [comment]
Yes true, I should have thought about it. This answers also to my initial question regarding the use of GLM to pressure data. 

Thanks Todd.
