### ISSUE TITLE
Repeated Measures ANOVA

### ISSUE THREAD

**Issue by DWellsUWA** [0todd0000/spm1d#2]
Hi guys, 

I'm hoping to run a repeated measures ANOVA on the following dataset. Is this possible with the current version of spm1d? I am running the MATLAB version of spm1d.

Independent variable: tester experience (session 1: experienced; session 2: inexperienced)
Dependent variable: elbow flexion/extension (time varying and normalised to 101 pts)
nSubjects = 10
nSessions = 2
nTasks = 1
nRepetitions = 12 per person per session 

Thanks!

**Comment by emiltn** [comment]
Hi,
First of all, thanks for a great work.

I was hoping to compare two independent groups using a continuous data; a comparison of knee flexion angle (normalized to a 0-100% of the motion) between an intervention group and a control group. I would like to identify if and where during the normalized motion there is a statistical difference between the groups. Each subject have repeated the motion between 3-5 times. I have previously used mixed-model to take into account repeated measures for these kind of cases - but I believe SPM would be more ideal to avoid the multiple testing issue and falsified results. I could average these repeated trials and apply a two-sample mean t-test (spm1d.stats.ttest2), but then I will lose valuable information. Is it possible to include repeated measures in the "ttest2" and how, or can you recommend a different approach.

Thanks.

**Comment by 0todd0000** [comment]
Hi, sorry for the delayed reply.  This issue has been closed, so is no longer checked. I have moved your question to a new issue:  #101
