### ISSUE TITLE
Y-axis normalized data

### ISSUE THREAD

**Issue by GabriellaSelena** [0todd0000/spm1d#202]
Hello!!
I am a PhD student working on gait analysis of dogs. Since dogs are fairly variable in size and shape, it is common practice to normalize waveforms along the y-axis in addition to time normalization, to reduce the variability between dogs. To do this we calculate a grand mean by subtracting an individual's mean value at each time point from the groups mean (Y0 -YA) then add this factor to each time point for every trial. 

I wanted to see how SPM responded to grand mean normalized data and I am fairly confused by the result.

Pre-normalized
![Screen Shot 2021-11-29 at 12 17 44 PM](https://user-images.githubusercontent.com/95773051/148285108-3c0c1d5c-90e0-44a3-9920-6affbe2a06bd.png)

Normalized
![SPM_ALL Results](https://user-images.githubusercontent.com/95773051/148285135-03920b16-80a7-43ed-ba62-24586d4c65c9.png)

Any thoughts would be greatly appreciated. 
Thanks so much, 
Gabriella

**Comment by 0todd0000** [comment]
Hi Gabriella,
The post-normalization F values are extremely large (10^30), indicating that variance is close to zero. This suggests that the normalization procedure may be inappropriate. 
Todd

**Comment by GabriellaSelena** [comment]
Thanks Todd, this makes sense. 

Follow up question: at least in canine gait analysis it can be common to see waveforms that are shifted vertically, but that aren't apparently different. 
Example:
![image_2022-01-05_174501](https://user-images.githubusercontent.com/95773051/148300293-d1114d91-d0d9-415f-8064-402691fe9b37.png)
SPM results on the data above
![Elbow SPM_RM_nonparaANOVA jpg](https://user-images.githubusercontent.com/95773051/148300706-e7c64353-f329-447d-b87a-308bd4b18afc.jpg)

From my playing around with SPM, it seems like it is sensitive to considering these shifts as significant- but I'm really trying to gauge how similar the waveforms are to each other. I guess I am wondering if SPM is the best fit, or if I've misinterpreted how SPM works.

**Comment by 0todd0000** [comment]
For ANOVA, SPM tests the null hypothesis of equivalent means, so if the means are very different (even if simply shifted), the results will generally be significant.

The only way to change this behavior in classical ANOVA is to make the means more similar. For example: subtract the group's grand mean value from each observation in that group. This will vertically shift all observations so that the 1D group means all have mean values (across time) of zero.

**Comment by GabriellaSelena** [comment]
Got it! I tried this and it indeed worked. Thank you so much!

Final question, unrelated: when doing post-hoc t-tests should one load each observation or just the mean for each subject?

Thanks again for all of your help!

**Comment by 0todd0000** [comment]
Common post hoc analyses use all observations. To see why, imagine ANOVA with just two groups. This is equivalent to a two-sample test;  both use all observations.

More generally, post hoc analyses can include any and all kinds of analyses, so you could indeed consider just the means if you like. But the usual post hoc procedures --- which generally replicate the main ANOVA results --- do indeed consider all observations.

**Comment by GabriellaSelena** [comment]
Ah- Again this makes sense. Thank you again and again :)

**Comment by 0todd0000** [comment]
No problem!  I'll close this issue for now, but please feel free to re-open it or create a new issue if anything else comes up.
