### ISSUE TITLE
Time normalization necessary?

### ISSUE THREAD

**Issue by k-bill** [0todd0000/spm1d#205]
Hi Everybody,

I hope this forum is where I can ask this question.

Is it possible to apply SPM to the first 100 ms of stance in three different cutting maneuvers, or do the cutting maneuvers need to be time normalized? Since I'm not only interested in the magnitudes of the joint moments but also in the timing of the peaks etc., I was thinking that normalizing the data might wash out the timing differences.

Any clarification would be much appreciated!
Thanks a lot :)

**Comment by 0todd0000** [comment]
Difficult question!

I'd say: yes, it is possible to apply SPM to the first 100 ms, and also yes: the cutting maneuvers need to be time normalized. If you are only interested in the first 100 ms, then discard subsequent data, and you will be left with a set of measurements, each 100 ms long. One could regard these as "time normalized" if time=0 is homologous (i.e., movement start, or another key instant) across all measurements.

More generally, it is indeed possible to either separately or simultaneously consider amplitude and timing effects. We currently have a paper in review that demonstrates how, and the corresponding software will be made available in the next major release of **spm1d**.

**Comment by k-bill** [comment]
Can't thank you enough for your quick answer, it was really helpful and I'm looking forward to reading the paper :)
