### ISSUE TITLE
Reporting SPM results

### ISSUE THREAD

**Issue by tnsavage** [0todd0000/spm1d#206]
Hi Todd and spm1d support team,

We have been using spm1d to determine differences between groups using both a t-test and GLM with covariates. I often get comments from co-authors about including the other two parts of the ‘holy trinity’ as per current convention for discrete statistics: the effect size and measures of precision. I understand from previous postings that the SPM graphs are best for effect size (issue [48](https://github.com/0todd0000/spm1d/issues/48)). For measures of precision, I read Mark’s posting (issue [143](https://github.com/0todd0000/spm1d/issues/143)) advocating use of spm1d's CI functionality when using an ANOVA, which would work with a t-test, or instead of a t-test, but is there anyway to calculate confidence intervals for the difference between groups for a GLM using spm1d? Or can the CI just be calculated from the mean difference between the groups over the suprathreshold range as an estimate even though a suprathreshold range doesn't necessarily determine a local effect?

Thanks for your help

Trevor

**Comment by 0todd0000** [comment]
For normal CIs you can use:

- spm1d.stats.ci_onesample
- spm1d.stats.ci_pairedsample
- spm1d.stats.ci_twosample

There are also nonparametric versions:

- spm1d.stats.nonparam.ci_onesample
- spm1d.stats.nonparam.ci_pairedsample
- spm1d.stats.nonparam.ci_twosample

See more details [here](https://spm1d.org/NewFeatures.html#label-confidenceintervals)

You should also be able to construct CIs for t contrasts from a GLM. You'd just need to transform the t-value and the SPM critical t-value back to the data units. This is not directly supported in **spm1d** so you'd need to calculate the transformation that is appropriate for your particular GLM.
