### ISSUE TITLE
Paired t test or two way ANOVA?

### ISSUE THREAD

**Issue by ShayneMV** [0todd0000/spm1d#210]
Scenario: Motion capture data is collected for overground running prior to and after completing a fatiguing protocol. Would running SPM paired t tests in the examples below result in an increased risk for family wise error? 
[Non-fatigued] - hip angle dominant limb vs hip angle non-dominant limb
[Fatigued] - hip angle dominant limb vs hip angle non-dominant limb
[Dominant limb] - non-fatigued hip angle vs fatigued hip angle
[Non-dominant limb] - non-fatigued hip angle vs fatigued hip angle

What would be the best test to use in this instance?
Thank you,

**Comment by 0todd0000** [comment]
It sounds like:
- There is one dependent variable (hip angle)
- There are two experimental factors (FATIGUE and LIMB)
- FATIGUE is repeated-measures (RM) factor
- LIMB is not an RM factor

If this summary is correct --- and presuming there are multiple subjects over which the RM measurements apply --- then the appropriate model is likely two-way ANOVA with one RM factor.  This is implemented in `spm1d.stats.anova2onerm`.  Here is an [example script](https://github.com/0todd0000/spm1d/blob/master/spm1d/examples/stats1d/ex_anova2onerm.py).

If you run a single analysis like this then the Type I error rate can be controlled using the `alpha` parameter as indicated in the script above.

If you instead skip to multiple *post hoc* analyses, then `alpha` generally needs to be adjusted.  (In this case, please search this forum for "post hoc" --- there are several discussions about *post hoc* analysis and a few of those  are directly relevant to this experimental scenario.)
