### ISSUE TITLE
reporting normality test results

### ISSUE THREAD

**Issue by eleonora-mont** [0todd0000/spm1d#211]
Hi Todd, 

I run the spm1d normality test on my 1d data, and I was wondering if there is a particular format to report it within the the figure caption? Because I am submitting both my thesis and papers with these, I wanted to be as precise as possible. 

![image](https://user-images.githubusercontent.com/79143162/165733478-c782fed5-5a7e-4d0b-b624-078c29aa1428.png)

At the moment, I just wrote that those images are 1d normality tests on the data residuals. 

Thank you,
Eleonora

**Comment by 0todd0000** [comment]
Hello! For a paper I think it would be fine to just report that "normality tests failed to reach significance at alpha=0.05, suggesting insufficient evidence against the null hypothesis of normality." For a thesis it might be nice to add figures like the ones you attached along with the statement above, perhaps adding that the normality test considers only the residuals (middle panel).

**Comment by eleonora-mont** [comment]
Will do this! Thank you so much Todd!
