### ISSUE TITLE
anova2onerm - "Design must be balanced"

### ISSUE THREAD

**Issue by ruddbull** [0todd0000/spm1d#213]
Hi all,

When I run anova2onerm I get the message "Design must be balanced". Does it comes from my uneven number of participants for my within and in between factors?

cheers

**Comment by 0todd0000** [comment]
Yes, **spm1d** currently only supports balanced designs. One way around this issue is to impose balance by randomly selecting N individuals from the larger group, where N is the size of the smaller group, then repeating for several random subsets to verify the numerical stability of the results.

**Comment by ruddbull** [comment]
Thank you for your reply.

**Comment by Sandra29200** [comment]
Hello Dr Pataky,
I would like to know if you plan to work on the possibility to use spm on balanced design? Thank you very much for answering ;)

**Comment by 0todd0000** [comment]
Support for balanced design already exists, you should be able to run all balanced designs using **spm1d**. A future version of **spm1d** will support unbalanced designs; please see this and other in-development functionality in the [spm1d feature requests](https://github.com/0todd0000/spm1d/issues/45) list.

**Comment by Sandra29200** [comment]
Sorry i was talking about unbalanced design. Do you know when the future version of spm would be available?
