### ISSUE TITLE
multiple regression analysis

### ISSUE THREAD

**Issue by Xlcandy** [0todd0000/spm1d#214]
Hi, there

   I am trying to examine the correlation between the peroneal longus, tibialis anterior, soleus muscles (3 independent variables) and the COP mediolateral displacement (1 dependent variable) during gait. After watching SPM Workshop, I feel that Canonical correlation analysis seems possible, but I found in [spm1d.org](http://spm1d.org/) about CCA, said that "spm1d currently does not support multivariate regressors." I would like to know when multiple regression analyses will be available using spm1d. And if you think there are any other better ways to analyze, I would be very appreciative of your advice.

Thanks!

**Comment by 0todd0000** [comment]
>  I would like to know when multiple regression analyses will be available using spm1d.

I would like to say soon, but it may be one year or more.

> And if you think there are any other better ways to analyze, I would be very appreciative of your advice.

It depends whether the dependent variable (COP mediolateral displacement) is a scalar or not. If it is a scalar, then you can use CCA, simply by swapping the independent and dependent variables. If it is not a scalar, then spm1d currently does not support that type of analysis.

**Comment by 0todd0000** [comment]
[This script for 0D data](https://github.com/0todd0000/spm1d/blob/master/spm1d/examples/stats0d/ex_cca.py) and [this script for 1D data](https://github.com/0todd0000/spm1d/blob/master/spm1d/examples/stats1d/ex_cca_Dorn2012.py) demonstrate how the data should be organized.

The basic function call is:

```python
x2 = spm1d.stats.cca(y, x)
```

- The `x` variable should be a `J`-element 1D array, or equivalently an array with size`(J,)`.
- For 0D data the `y` variable must be a `(J,I)`2D array.
- For 1D data the `y` variable must be a `(J,Q,I)`3D array.

Here:
- `J` : number of observations
- `Q` : number of time nodes
- `I` : number of vector components

**Comment by Xlcandy** [comment]
Thank you so much!!

**Comment by Xlcandy** [comment]
> * The `x` variable should be a `J`-element 1D array, or equivalently an array with size`(J,)`.
> * For 0D data the `y` variable must be a `(J,I)`2D array.
> * For 1D data the `y` variable must be a `(J,Q,I)`3D array.
> 

Hi!

I would like to ask how to create a `(J)`-element 1D array using EXCEL.
![image](https://user-images.githubusercontent.com/104749353/167769224-b41286bd-373c-42dc-9c78-344b28b5eadc.png)
![image](https://user-images.githubusercontent.com/104749353/167769277-641267ce-de16-4e4b-b2f5-f441e998b1f9.png)

Both of these two are 2D array...


Thank you!!

**Comment by 0todd0000** [comment]
If a 2D array has just one column or one row (i.e., with shape `(J,1)` or `(1,J)`) you can convert it to a 1D array using the [`flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) method:

```python
import numpy as np

x0 = np.array( [ [1, 3, 5] ] )
x1 = np.array( [ [1], [3], [5] ] )

print( x0.shape )
print( x1.shape )

x0 = x0.flatten()
x1 = x1.flatten()

print( x0.shape )
print( x1.shape )
```

Output:

```
(1, 3)
(3, 1)
(3,)
(3,)
```

**Comment by Xlcandy** [comment]
Thank you Todd!!

**Comment by 0todd0000** [comment]
I received an email regarding a plot command error but do not see the question here... please repost if the issue has not yet been resolved.
