### ISSUE TITLE
reporting nonparam linear regression of pressure images

### ISSUE THREAD

**Issue by eleonora-mont** [0todd0000/spm1d#221]
Hi Todd,

I have run nonparametric linear regression between pressure images and some independent variables (e.g. body weight). In the report of the results, I have been asked to be as transparent as possible when reporting the statistical results but I am not sure what this means as I just reported the t values present also in the figures. Is there a specific way to report the results and which parameters do you normally advise to report? At the moment, I am reporting t values and discussing the results as positive/negative relationship, but I have been asked whether R values can be reported too. I believe there might be confusion on behalf of my readers as they might be thinking about standard discrete regression analysis. 

Thanks for your help as always.

Eleonora

**Comment by 0todd0000** [comment]
I also don't know what "transparent" means. Perhaps reporting the raw statistical field (i.e., the t-values before thresholding) would be sufficient?  I'd suggest asking the person who made this request to clarify what they mean by "transparent".

Yes, r-values can also be reported. You can access these values from `spm.r` when the analysis is a correlation analysis (e.g. `spm1d.stats.regress`). The transformation between r-values and t-values is (Python code):

```python
r = ( t**2 / (n - 2 + t**2 )  )**0.5
```

where `n` is the sample size.

The only difference between t-values and r-values is their ranges: the t-value range is [-infinity, +infinity] and the r-value range is [-1, +1].  This generally makes large r-values (>0.9) difficult to distinguish. For example:  r=0.90 and r=0.99 are generally difficult to distinguish in a color map that ranges from r=-1 to r=+1, but r=0.99 is clearly a much stronger correlation. Using t-values with color maps generally retains a better connection between visual perception and correlation strength. So I personally find t-values to be more informative and transparent than r-values.

**Comment by eleonora-mont** [comment]
Hi Todd,

Thanks for your reply. Thing is, I calculated a correlation matrix among my independent variables before the regression analysis, so I had already r values discussed. For the regression, I think I'll go just for the t-values, explaining my results as positive and negative relationship if that sounds ok. 

Thanks again,
Eleonora

**Comment by 0todd0000** [comment]
OK, that sounds fine and also suitably transparent.
