### ISSUE TITLE
anova2rm gammaln error

### ISSUE THREAD

**Issue by jeannedury** [0todd0000/spm1d#223]
Hi, 
I try to used the anova2rm function for spm analysis but I meet the following error message: 
<img width="599" alt="erreur" src="https://user-images.githubusercontent.com/109362626/179247863-c866df4a-ada1-4ea0-b67d-b1b46491620c.png">

Do you have any idea to resolve the problem ? 
Thank you very much.

**Comment by 0todd0000** [comment]
I've not seen this error so I'm not sure what is causing the problem. Can you please enter `disp( spmilist )` and copy the output here?

**Comment by jeannedury** [comment]
I tried to enter disp ( spmilist), the output is below :
>> disp(spmilist)
Unrecognized function or variable 'spmilist'.
 
Did you mean:
>> disp(spmlist)

So I tried with disp (spmlist) and the output is this one : 
  SPMFList with properties:

           design: 'ANOVA2rm'
         nEffects: 3
    effect_labels: {'Main A'  'Main B'  'Interaction AB'}

**Comment by jeannedury** [comment]
Many thanks for your quick response. 
I think I had not organized my data properly with repeated and independent factors because now It work!

**Comment by 0todd0000** [comment]
No problem!
