### ISSUE TITLE
".clusters" command: can I get the width of the significant clusters ?

### ISSUE THREAD

**Issue by Xlcandy** [0todd0000/spm1d#228]
"***.clusters" command returns detailed information about the significant clusters including endpoints.
Can I get the "width"(larger endpoint minus smaller endpoint) of the individual clusters in a simple way?
And I would like to get the sum of all significant cluster widths in a single t-test result.

<img width="495" alt="截屏2022-09-16 上午11 47 16" src="https://user-images.githubusercontent.com/104749353/190546285-cf782621-f30f-41ee-8936-9a500555718a.png">

**Comment by 0todd0000** [comment]
Try using `spmi.extent` to get the width of a single cluster.

I suggest using a list comprehension to get the widths of all clusters, like this:

```python
extents = [c.extent for c in spmi.clusters]
```

or getting the total excursion set extent as:

```python
total_extent = sum( [c.extent for c in spmi.clusters] )
```

However, please note that there is no straightforward parametric probability for `total_extent`; its probabilistic meaning is somewhat elusive. Thus I do not recommend using `total_extent` for reporting purposes.

**Comment by Xlcandy** [comment]
Okay! I got it.
Thank you very much, Todd!
Have a nice day!

**Comment by 0todd0000** [comment]
🙂
