### ISSUE TITLE
Unbalanced number of repeats across individuals

### ISSUE THREAD

**Issue by MinaKhajooei** [0todd0000/spm1d#229]
Hi,

I have a question regarding performing test for individuals with unequal number of repeats.
As I understood I need to perform random effects analysis for this kind of data but the question is that does SPM support this kind of analysis?

Thanks in advance
Mina

**Comment by 0todd0000** [comment]
Sorry for the delay!

It depends what you mean by "repeats". If you mean "repeated across multiple conditions" then this may be a repeated-measures design in which case **spm1d** may indeed support it. If you mean "repeated within a single condition" then it is usually sufficient to simply calculate within-condition means for each subject.
