### ISSUE TITLE
Vector field analysis and joint coordinate system

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#23]
Dear Todd,

I read with interest the paper "Vector field statistics for objective center-of-pressure trajectory analysis during gait, with evidence of scalar sensitivity to small coordinate system rotations". 

 One can define angles/moments based on the proximal, distal, joint, lab coordinate system. Based on the CS used, one can lead to varying conclusions. Can vector field help in this case?

I appreciate your help :)

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
Yes, vector analyses (i.e. multivariate analyses) can help because they are CS-independent.  In other words, you can rotate the CS arbitrarily and the multivariate results will be constant.
Todd

**Comment by bernard-liew** [comment]
Thanks Todd,

Great help and I think this can be closed.

Regards,
bernard
