### ISSUE TITLE
Can we use G*power for sample size when the SPM approach is used?

### ISSUE THREAD

**Issue by Lukasslovak** [0todd0000/spm1d#230]
Dear Todd, dear colleagues,

I get the comments from the reviewer:
 
“ I don’t think a power analysis (G*power) based on a repeated measures ANOVA is applicable to statistical parametric mapping. Statistical parametric mapping is based on random field theory, whereas ANOVAs are based on the general linear model”
 
**Question: Can we usually perform G*power analysis establishing the sample size where the SPM approach was used?**

Hope this topic helps to other young researchers :-)

With honor, Lukas

**Comment by 0todd0000** [comment]
In general: no, G*power can not be used to establish sample size for SPM analysis. However, that doesn't necessarily mean that G*power's results are incorrect.

If trajectory-level analyses like SPM are conducted, then trajectory-level power methods are required to calculate sample sizes. **G*Power** does not include trajectory-level calculations so in general cannot be used to calculate power for trajectory-level analyses.

There are several methods and packages for conducting trajectory-level power analyses, for example: [power1d](https://spm1d.org/power1d/). The key difference between trajectory-level power analyses and 0D power analyses (i.e., the type of power analysis conducted in **G*Power**
