### ISSUE TITLE
Which normality test is used?

### ISSUE THREAD

**Issue by McBanana33** [0todd0000/spm1d#235]
Hello Mr. Pataky, 

which normality test do you use in this code (it's your example from file: ex1d_anova1.m)?

" clear;  clc

%(0) Load data:
dataset  = spm1d.data.uv1d.anova1.SpeedGRFcategorical();
% dataset  = spm1d.data.uv1d.anova1.Weather();
[y,A]    = deal(dataset.Y, dataset.A);

%(1) Conduct normality test:
alpha     = 0.05;
spm       = spm1d.stats.normality.anova1(y, A);
spmi      = spm.inference(0.05);
disp(spmi)

%(2) Plot:
close all
figure('position', [0 0  1200 300])
subplot(131);  plot(y', 'k');  hold on;  title('Data')
subplot(132);  plot(spm.residuals', 'k');  title('Residuals')
subplot(133);  spmi.plot();  title('Normality test')"

On your website I've seen that you support the D’Agostino-Pearson K2 test as well as the Shapiro-Wilk. Which one is it in this example? 
Thank you!

**Comment by 0todd0000** [comment]
It appears from your code that you are using the MATLAB version of **spm1d**, in which case only the K2 test is supported. This is shown in the source code, for example [this file](https://github.com/0todd0000/spm1dmatlab/blob/master/%2Bspm1d/%2Bstats/%2Bnormality/anova1.m) for the `anova1` normality test. 

In the Python version of **spm1d**, by default the K2 test is used as shown in the normality sub-package's [`__init__.py`](https://github.com/0todd0000/spm1d/blob/master/spm1d/stats/normality/__init__.py) file. In Python you can alternatively run a SW test by adding `sw` between `normality` and the test name like this:

```python
spm = spm1d.stats.normality.sw.anova1(y, A)
```

**Comment by McBanana33** [comment]
Great, thanks for the response!
