### ISSUE TITLE
How should we cite the library in a scientific paper?

### ISSUE THREAD

**Issue by stamstamNitzan** [0todd0000/spm1d#236]
Hey,
I was wondering what is the correct way to cite the library (or website) in a scientific paper when someone uses it?

All the best, Nitzan

**Comment by 0todd0000** [comment]
Thank you for this question and for checking!  There isn't a standard way of citing it, but it would be fine to follow [this discussion on general GitHub guidelines](https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository).

For an academic paper please cite one of the papers listed in the [References](https://spm1d.org/References.html) section of spm1d.org. 

One or both of these is probably best as a software citation:

- Pataky TC (2012) [One-dimensional statistical parametric mapping in Python.](https://www.researchgate.net/publication/51491994_One-dimensional_statistical_parametric_mapping_in_Python) Computer Methods in Biomechanics and Biomedical Engineering. 15, 295-301.
- Pataky TC (2016). [rft1d: Smooth one-dimensional random field upcrossing probabilities in Python](http://dx.doi.org/10.18637/jss.v071.i07), Journal of Statistical Software, 71(7): i07.

<br>
<br>

If you are using MATLAB and would prefer that "Python" does not appear in the title then this paper would be fine too.

- Pataky TC (2010). [Generalized n-dimensional biomechanical field analysis using statistical parametric mapping.](https://www.researchgate.net/publication/43533754_Generalized_n-dimensional_biomechanical_field_analysis_using_statistical_parametric_mapping?ev=prf_pub) Journal of Biomechanics 43, 1976-1982.

**Comment by stamstamNitzan** [comment]
Great
Thank you!
