### ISSUE TITLE
Sample size calculation

### ISSUE THREAD

**Issue by SimonBarruebelou** [0todd0000/spm1d#237]
Hello,

We are currently working on a descriptive project in which we would like to publish normative data of a continuous variable (torque-angle relationship).
The first step of our work is a pilot study, because we do not already know the variability of the data in the population through the entire range of motion. So, we decided to include 2 groups of 35 subjects (sex stratification), in order to observe the variability between the subjects and with the aim of calculate the sample size necessary to obtain normative data in a next study. Our idea was to realize several sample size calculations, corresponding to different desired power (0.8 to 0.95, for example).

We are going to manipulate the data with SPM, to compare groups and conditions.
But for a priori sample size calculation, I’m wondering if I have different possibilities or not :
- the first idea was to calculate the sample size using the « worst case », the point through the continuous data at which the standard deviation is maximal. And calculate from this point.
- but maybe, have we got any possibility to use an already developed script which permits to calculate the sample size for a continuous one-dimensional variable ?

Many thanks in advance for your help

Simon

**Comment by 0todd0000** [comment]
Your solution is certainly one possibility. Another possibility is to use scaled noise, as demonstrated in the [scaled noise example](https://spm1d.org/power1d/API/noise.html#scaled) from [power1d](https://spm1d.org/power1d). This noise model can be used to scale another type of noise (e.g., smooth gaussian), and the scale itself can be a 1D array, like the standard deviation from a pilot study.

- but maybe, have we got any possibility to use an already developed script which permits to calculate the sample size for a continuous one-dimensional variable ?

Sample-size calculations require the definition of a 1D effect, which can be most easily constructed using a 1D noise model and a 1D signal model. Please refer to [this example](https://spm1d.org/power1d/Examples/SampleSize.html).
