### ISSUE TITLE
Data "normalization"

### ISSUE THREAD

**Issue by KevinGiordano** [0todd0000/spm1d#239]
I am seeking your advice on accounting for variables in SPM regression, specifically “mass normalizing.”  I am currently working on a paper attempting to predict a dependent variable of shoulder torque during pitching and would like to calculate results after accounting for varying body mass.  Standard in the field is to divide torque by kg body mass to get a “normalized torque” measurement, which is not an appropriate way to handle that (Curran 2013; Allison 1995; Hirsch 2022).  In regression, without time series data, I would perform this by comparing the models torque ~ kg and torque ~ kg + IV to determine the effects of the independent variable.  Is there a way to perform this with SPM?

**Comment by 0todd0000** [comment]
One way to do this is with a covariance model via the `spm1d.stats.glm` function, as illustrated in [this example](https://spm1d.org/doc/Stats1D/onetwosample.html#general-linear-model-glm).  You can include any number of covariates you like, including body mass, then compare the results to the identical model without that covariate.

**spm1d** does not support direct model comparison but I expect that a qualitative comparison of the models' results would be sufficient. Another limitation is that **spm1d** only supports t-contrasts (not F-contrasts) so full ANCOVA is not yet possible.

**Comment by KevinGiordano** [comment]
Very helpful, thank you!
