### ISSUE TITLE
p-value of non significant results

### ISSUE THREAD

**Issue by LeSensduMouvement** [0todd0000/spm1d#240]
Hello, 
I'm currentely using SPM1D package with Python, performing several paired t-tests with my data. I would like to include p-values of non significant results to my results discussion, as it is possible with 0D statistics. Although I can find p-values of significant results, I couldn't find it for non significant results. 
I was wondering if I missed something or if in SPM, p-value of non significant results weren't available or pointless. 
Maybe could you advise me more relevant data from SPM analysis to discuss non significant results? 

Thank you!

**Comment by 0todd0000** [comment]
Please refer to issues #222 and #191 for relevant discussions.

To summarize those discussions:
- Usually only cluster-level p-values are reported, but clusters do not exist when p > alpha.
- It is indeed possible to calculate p-values for non-cluster quantities, and the most common quantity is the maximum test statistic value. This probability can be calculated using the `rft1d.t.sf` function as demonstrated in [this script](https://github.com/0todd0000/spm1d/blob/master/spm1d/rft1d/examples/val_max_1_onesample_t_1d.py), but note that (a) this probability is generally valid only for p < 0.5 and (b) it is different from cluster-level probabilities so it cannot be directly / meaningfully compared to cluster-level results.

**Comment by ShengxingFu** [comment]
Hello，
I used One-dimensional SPM two-way ANOVA with repeated measures on one factor to assess differences between groups across times. However, there was no significant interaction effect of group and time or group effect. I would like to include a specific P-value of the non-significant interaction effect of group and time or non-significant group effect in my study. Could you tell me how to calculate the P-value？

Thank you very much!

**Comment by 0todd0000** [comment]
Provided you have used parametric inference, please use `rft1d.t.sf` to calculate p-values for specific test statistic values. BUT note that these p-values may not be accurate when they are large (e.g. p>0.4). 

Below is a modification of the [anova2 example script](https://github.com/0todd0000/spm1d/blob/master/spm1d/examples/stats1d/ex_anova2.py)

```python
import numpy as np
import spm1d

def pmax_f(spm):
    from spm1d import rft1d
    zmax = spm.z.max()  # maximum test statistic value
    df   = spm.df       # degrees of freedom
    Q    = spm.Q        # number of domain nodes
    fwhm = spm.fwhm     # smoothness estimate
    p    = rft1d.f.sf(zmax, df, Q, fwhm)  # RFT survival function
    return p

dataset = spm1d.data.uv1d.anova2.SPM1D_ANOVA2_2x3()
y,A,B   = dataset.get_data()
spms    = spm1d.stats.anova2(y, A, B, equal_var=True).inference(0.05)
pmax    = [pmax_f(spm)  for spm in spms]
print( pmax )
```

<br>
<br>

This yields the result:

```
[0.3677, 0.009, 0.3114]
```

These are p-values for the maximum F-values from each of the **anova2** effects.

**Comment by ShengxingFu** [comment]
Hello, 
Thanks for your help. However, there are many rft1d codes in the downloaded MATLAB source code from https://spm1d.org/index.html#. Which is the related rft1d code? 
![image](https://github.com/0todd0000/spm1d/assets/143973952/e2f759c9-0e38-4aaf-98ce-d05dc3d117a7)

**Comment by 0todd0000** [comment]
`rft1d.f` is appropriate for ANOVA. "f" means the "F statistic".
