### ISSUE TITLE
Two within-subjects factors repeated measures ANOVA

### ISSUE THREAD

**Issue by meteor77** [0todd0000/spm1d#242]
Hello,

I was looking to perform a two within-subjects factor repeated measures ANOVA however in the MATLAB repository files I did not find any examples. Have I missed it or is it that you don't have them?

Shahab

**Comment by 0todd0000** [comment]
Hi Shahab,

The relevant procedure is `spm1d.stats.anova2rm`. Please find example scripts here:

0D data:
[./spm1d/examples/stats0d/ex_anova2rm.m](https://github.com/0todd0000/spm1dmatlab/blob/master/examples/stats0d/ex_anova2rm.m)


1D data:
[./spm1d/examples/stats1d/ex1d_anova2rm.m](https://github.com/0todd0000/spm1dmatlab/blob/master/examples/stats1d/ex1d_anova2rm.m)
