### ISSUE TITLE
install SPM1d

### ISSUE THREAD

**Issue by yossy-biomech** [0todd0000/spm1d#245]
Please tell me how to solve the problem that I cannot install.
I bought a new Apple M1Max and tried to install SPM1d.

The software versions used are:
conda version : 22.11.1
conda-build version : 3.22.0
python version : 3.9.13.final.0

I typed:
’conda install -c toddp spm1d’

Then the following message appeared and installation failed.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - spm1d

Current channels:

  - https://conda.anaconda.org/toddp/osx-arm64
  - https://conda.anaconda.org/toddp/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by 0todd0000** [comment]
Please try:
```
pip install spm1d
```
That should work even if the conda install fails.

**Comment by yossy-biomech** [comment]
Thank you.
Installation was successful.
