### ISSUE TITLE
Installing "power1d"

### ISSUE THREAD

**Issue by Yokonie** [0todd0000/spm1d#248]
Hi,

This might be a very silly question but I am really new to Python and have been struggling with installing "power1d".

I have not had a problem with using "spm1d". However, when I tried to install "power1d", the error occurs as you can see from the image below.
![Screen Shot 2023-02-05 at 13 48 21](https://user-images.githubusercontent.com/115612562/217137630-dbbc1ef9-312e-43e4-b2af-afd9ebbe83f4.png)

I updated Python to the latest version and installed all the dependencies based upon instructions given from this link https://spm1d.org/power1d/index.html. However, I have not been able to install power1d.

Any help or guidance would be greatly appreciated!

Yoshi

**Comment by 0todd0000** [comment]
My apologies!  **power1d** was offline for testing and development purposes.  It is now active once again:
https://pypi.org/project/power1d/

So please try to install once again using:

```
pip install power1d
```

Note:  the example scripts are NOT included in the new version (version 0.1.6). If you require the example scripts please access them from the repository here:
https://github.com/0todd0000/power1d

**Comment by Yokonie** [comment]
Thanks for the prompt reply!
I just installed it. Thanks for your help!

Yoshi
