### ISSUE TITLE
Comparison of multiple groups using spm1d

### ISSUE THREAD

**Issue by TakumaInai** [0todd0000/spm1d#249]
Dear Dr. Todd,

I have a basic queation.
Now, I want to compare waveforms in 3 conditions.
For example,
n = 28
Condition 1: Normal walking
Condition 2: Slow walking
Condition 3: Fast walking
Variable: Knee sagittal joint angles (one gait cycle)

Can I use spm1d to compare the knee sagittal joint angle waveforms between 3 conditions?
If it is possible, would you tell me how to conduct it? 

Sincerely yours,
Takuma Inai
AIST

**Comment by 0todd0000** [comment]
Hello Takuma,
Yes, spm1d can be used to compare three conditions. It sounds like the appropriate function is one of the following:
- **spm1d.stats.anova1**: one-way ANOVA; if different subjects performed the three conditions
- **spm1d.stats.anova1rm**: one-way repeated-measures ANOVA; if each subject performed all conditions.
 
Here are links to examples:
- [anova1 example](https://spm1d.org/doc/Stats1D/anova.html#one-way-anova)
- [anova1rm example](https://spm1d.org/doc/Stats1D/anova.html#one-way-repeated-measures-anova)

Press "Source code" at the links above to download full scripts.
