### ISSUE TITLE
How to use corresponding SPM analysis for coordination variability

### ISSUE THREAD

**Issue by HelloBeer** [0todd0000/spm1d#251]
First I quantified the coordination variability under three different tasks using standard deviation, so that there are only 101 data points of variability for each task, and I want to get the correlation report of the standard deviation under these three tasks.

In spm1d I see “ex1d_cca.m&ex1d_manova1.m”,but I can't understand how the author set up the dataset,I think it may be a simple and stupid question,but it does give me a lot of trouble,I hope to get your help.

I'm not sure I've explained my doubts clearly, if not please let me know!

Thank you ~

![Coordination Variability](https://user-images.githubusercontent.com/116572574/226178990-83a72b5a-fa72-4ac8-b77b-2f76f45a4e10.png)

**Comment by 0todd0000** [comment]
The procedure **spm1d.stats.eqvartest** can be used to test for the equality of variance between two samples. Please find a description of the procedure and a relevant literature reference in the source code here:
https://github.com/0todd0000/spm1d/blob/master/spm1d/stats/var.py

Notes:
1. You must submit the entire data sample (i.e., all observations from both samples) to the procedure, and not just the estimated variance or standard deviation.
2. It is currently only possible to compare two samples. A future version of **spm1d** may support more samples.

**Comment by HelloBeer** [comment]
Thank you very much for your reply, I can't wait to try it out.
