### ISSUE TITLE
Two way ANOVA for repeated measures

### ISSUE THREAD

**Issue by MauriGiorgio** [0todd0000/spm1d#252]
Hi, 
I have to analyze in Matlab a database made up of two different groups of subjects: one group for control with 9 subjects and the other one subjected to a session of training with 10 subjects and for each of them were carreid out two measurements at two different instants of time.
I need to do a Two-way ANOVA for repeated measures in order to compare the results, but all the codes I've found ask in input two groups with the same number of subjects and I want to know if there is a code to perform that type of Anova even if the two groups are numerically different.
Thank you.

**Comment by MauriGiorgio** [comment]
Thank you, I have already used that function in Matlab but it doesn't work because the two groups are unbalanced (9 subjects control and 10 subjects training).

**Comment by m-a-robinson** [comment]
Yes that is correct I'm afraid. spm1d only works with balanced designs at the moment. See this discussion https://github.com/0todd0000/spm1d/issues/213 and timeline for further brief comment.
