### ISSUE TITLE
Order of dataset ttest2

### ISSUE THREAD

**Issue by MauriGiorgio** [0todd0000/spm1d#256]
Hi, 
I am doing an analysis about the differences between two groups of objects (group A and group B) with the ttest2 (unpaired ttest) in Matlab but I have noticed that it gives me different results  depending on the order in which I enter the inputs ( A and B or B and A).
Is it correct? if it was correct, in what order should I enter the inputs?

**Comment by 0todd0000** [comment]
Swapping the order of the input arguments like this:

```octave
spm1 = spm1d.stats.ttest2(yA, yB);
spm2 = spm1d.stats.ttest2(yB, yA);
```

should yield **opposite** results in the sense that the t statistics should have **opposite** signs. Thus the following statement should be true at all time points:

```octave
spm1.z == -spm2.z
```

Other than this no difference is expected.  If you are indeed seeing different results please paste code and/or a figure into this issue thread.

**Comment by MauriGiorgio** [comment]
Thanks for the reply.
For the parametric test, the results don't change (The results have opposit
signs and the same t* value).
However, for the non parametric test, if I change the order of A and B, the
results are different, in particular the t* values calculated by the code
change.
The code that I am using is here:
A=[]; A=table2array(Y(1:sss , 3:103 ));
B=[]; B=table2array(Y(sss+1:end , 3:103 ));
%(1) Conduct non-parametric test:
rng(0)
alpha = 0.05;
two_tailed = true;
iterations = 1000;
snpm = spm1d.stats.nonparam.ttest2(A, B);
snpmi = snpm.inference(alpha, 'two_tailed', two_tailed, 'iterations',
iterations);
disp('Non-Parametric results')
disp( snpmi )
%(2) Compare to parametric inference:
spm = spm1d.stats.ttest2(A, B);
spmi = spm.inference(alpha, 'two_tailed',two_tailed);
disp('Parametric results')
disp( spmi )
% plot:
figure('position', [0 0 1000 300])
subplot(121); spmi.plot(); spmi.plot_threshold_label();
spmi.plot_p_values();
subplot(122); snpmi.plot(); snpmi.plot_threshold_label();
snpmi.plot_p_values();
title(nomepar, 'Interpreter', 'none');
Here there are two examples, the plots on the left of each image are about
the parametric test and ones on the right are about the non parametric test.

Il giorno gio 20 apr 2023 alle ore 05:43 Todd Pataky <
***@***.***> ha scritto:

**Comment by 0todd0000** [comment]
The results will change for nonparametric permutation tests even if you don't change the input order. Permutation test results are based on randomly permuted observations so the results are not expected to be constant unless you both (a) keep all inputs constant and (b) control the random number generator (RNG) seed / state.

**Comment by 0todd0000** [comment]
Try not changing anything, even the variable order, and just run the nonparametric inference code several times. You will find that the t* value is not constant. This means that non-constant t* is caused by the algorithm itself and not by the variable order.

**Comment by MauriGiorgio** [comment]
I've tried running the code several times without changing anything, but
the value of t* doesn't change in the non-parametric test.
The value of t* changes only if I change the order of databases from A-B to
B-A.
(Values of data in A and B are always the same).

Il giorno mer 3 mag 2023 alle ore 19:39 Todd Pataky <
***@***.***> ha scritto:

**Comment by 0todd0000** [comment]
Please try running the following code.

```octave
% create dataset:
yA = randn(10,1);
yB = randn(10,1);


% conduct non-parametric test several times:
rng(0)
alpha      = 0.05;
two_tailed = true;
iterations = 1000;
for i = 1:5
    ti = spm1d.stats.nonparam.ttest2(yA, yB).inference(alpha, 'two_tailed', two_tailed, 'iterations', iterations);
    disp( ti.p );
end
```

<br>
<br>

You should see that the result `ti.p` changes each time the test is run.  The results should be:

<br>
<br>

```octave
    0.4940

    0.5160

    0.4840

    0.5140

    0.4580
```

<br>
<br>


If this does not help to solve your problem, please post code replicating the problem into this thread.

**Comment by 0todd0000** [comment]
> As I explained earlier, if I do the non-parametric 1d t-test2 I always get the same t* value.

This is only possible if you either (a) controlling the random number generator state, or (b) running all iterations. In either case it is not a problem, it is a feature of this non-parametric analysis approach.

<br>
<br>

> If I change the order of A and B the t* value changes.

Again, this may not necessarily be a problem, it may instead simply be a reflection of this non-parametric analysis approach.

<br>
<br>

I can only answer your questions more specifically if you attach specific code and specific results. Please copy-and-paste your code, and please add numbers to the following statements:

> I always get the same t* value.

- What is the t* value?  

> If I change the order of A and B the t* value changes.

- What is the t* value for the AB case?
- What is the t* value for the BA case?
- Does the t* value change if you run the AB and/or BA cases multiple times?

**Comment by MauriGiorgio** [comment]
Here there is the code that I use (A and B are always the same and thet're
the ones that I have sent before):

A=[]; A=table2array(Y(1:sss , 3:103 ));

B=[]; B=table2array(Y(sss+1:end , 3:103 ));



%(1) Conduct non-parametric test:

rng(0)

alpha      = 0.05;

two_tailed = true;

iterations = 1000;

snpm       = spm1d.stats.nonparam.ttest2(A, B);

snpmi      = snpm.inference(alpha, 'two_tailed', two_tailed, 'iterations',
iterations);

disp('Non-Parametric results')

disp( snpmi )





%(2) Compare to parametric inference:

spm        = spm1d.stats.ttest2(A, B);

spmi       = spm.inference(alpha, 'two_tailed',two_tailed);

disp('Parametric results')

disp( spmi )



% plot:



figure('position', [0 0 1000 300])



subplot(121);  spmi.plot();  spmi.plot_threshold_label();
spmi.plot_p_values();

subplot(122);  snpmi.plot(); snpmi.plot_threshold_label();
snpmi.plot_p_values();

title(nomepar, 'Interpreter', 'none');




1) If I use the order A-B (like in the code above) the t* value is always
2.253 .

     If I change the order B-A in the code the t* value is always 2.212.

I leave here the images of the plots of each case.



2) In both cases, the value of t* doesn't change if i run several time the
code.






Il giorno mar 9 mag 2023 alle ore 12:20 Todd Pataky <
***@***.***> ha scritto:

**Comment by 0todd0000** [comment]
> If I use the order A-B (like in the code above) the t* value is always 2.253

This is because you are using `rng` to control the random number generator state. Try changing `rng(0)` to `rng(1)` or `rng(2)` or `rng(n)` where `n` is any positive integer. The t* value should change.

**Comment by MauriGiorgio** [comment]
Ok, thank you very much

Il giorno mar 9 mag 2023 alle ore 13:44 Todd Pataky <
***@***.***> ha scritto:
