### ISSUE TITLE
Error in nonparam ttest_paired

### ISSUE THREAD

**Issue by mrrezaie** [0todd0000/spm1d#262]
Hi, sorry for this post. I have 2 conditions (J=20, Q=101) and intend to use `ttest_paired`. The data are angle, moment, and power. First, I checked the normality using `spm1d.stats.normality.ttest_paired(Con1,Con2).inference(0.05)` and in case of h0 rejection, I used non parametric test.

I found that there are two nonparametric versions of `ttest_paired`: `spm1d.stats.nonparam.ttest_paired` and `spm1d.stats.nonparam.stats.ttest_paired` and both methods seem identical. In any case and `force_iterations=True`, I get this error:
```
ValueError: setting an array element with a sequence. 
The requested array has an inhomogeneous shape after 1 dimensions. 
The detected shape was (1048576,) + inhomogeneous part.
```
This is my implementation:
```Python
spm1d.stats.nonparam.stats.ttest_paired(Con1,Con2).inference(
     alpha=0.05, two_tailed=True, force_iterations=True)
```
By default, `iterations=-1` which I presume there will be no limitation in the number of iterations and the spm1d version is 0.4.19.
Any idea what the problem is? I'm looking forward to hearing from you and any help is greatly appreciated.

Regards,
Mohammadreza

**Comment by 0todd0000** [comment]
Thank you for reporting the version number and also for a very clear description of the problem!

<br>
<br>

> I found that there are two nonparametric versions of ttest_paired: spm1d.stats.nonparam.ttest_paired and spm1d.stats.nonparam.stats.ttest_paired and both methods seem identical.

This is correct. `spm1d.stats.nonparam.ttest_paired` just points to the deeper `ttest_paired` function and doesn't itself contain any code.  Using `spm1d.stats.nonparam.ttest_paired` is just the quickest way to access the function.


<br>
<br>

Regarding the `ValueError`:
- From your description I gather that the full script looks something like this (with different`yA` and `yB` values of course):

```python
import numpy as np
import spm1d

np.random.seed(0)
yA  = np.random.randn(20, 101)
yB  = np.random.randn(20, 101)
tn  = spm1d.stats.nonparam.ttest_paired(yA, yB)
tni = tn.inference(0.05, two_tailed=True, force_iterations=True)
print(tni)
```

- This script does not generate an error on my computer so I'm not yet certain what is causing the error you're seeing
- Although I doubt that memory is a problem, it may indeed become a problem if you are running other memory-hungry applications at the same time.  To check can you please try running with fewer than all permutations, like this?

```python
tni = tn.inference(0.05, two_tailed=True, iterations=1000)
```

- Usually 10,000 or more permutations are needed for numerical stability, but using 1000 like this will be quick and may provide a clue regarding the source of the problem

**Comment by mrrezaie** [comment]
Thanks a lot for your response. Your example works well in my system, but the test doesn't work with my data. The error also occurs with lower iteration value and no memory-hungry application is active. May I please ask you to test this sample? [data.zip](https://github.com/0todd0000/spm1d/files/12049432/data.zip)
```Python
yA = np.load('data.npz')['con1']
yB = np.load('data.npz')['con2']
```
Also, I have a question about whether or not use nonparametric test. Please see the graph below (the uploaded data):
![Figure_1](https://github.com/0todd0000/spm1d/assets/38867713/7ba3aa94-8a7c-4c39-8d09-53133fb986b9)
The normality test indicates that the data are not normally distributed in two small regions after 60% of gait, and the **parametric** paired t-test reveals a significant difference between the conditions before 60% of gait. Since there is no overlap between the regions of significance for the two tests, it seems unreasonable to apply a nonparametric test to the entire data set. In other words, the data are normally distributed in the frames where the parametric test detects a significant difference. In this case, reporting the result of the parametric test doesn't seem incorrect. I would appreciate your feedback on this.

**Comment by mrrezaie** [comment]
Hi, I think I found the issue, please see my pull request https://github.com/0todd0000/spm1d/pull/263. I'm no longer getting the error.

**Comment by mrrezaie** [comment]
Hi, I found your thorough response in another post, on the use of parametric and nonparametric implementations:
https://github.com/0todd0000/spm1d/issues/173#issuecomment-848716020
Thank you.
