### ISSUE TITLE
SPM information

### ISSUE THREAD

**Issue by jeannedury** [0todd0000/spm1d#266]
Hello Todd, 

I have used the SPM method to process my data about jump landing with the spm1d package. I'm still wondering about several points concerning this processing. 

- Firstly, should sample normality be respected in order to use this analysis? 
- Also, as with more traditional statistical analyses, are effect size calculations possible? Is there a sample size calculation specific to these analyses?
- I've also seen on discussion forums that some researchers are integrating all jump trials into their analysis. In fact, I've calculated the average of the 5 jump trials performed and then used this average for the statistics. Is this a mistake?
- Finally, I've had a few discussions with colleagues about confidence intervals. Indeed, some of my data come out significant with the SPM treatment, but visually the graphs show an overlap of the 95% confidence intervals. I'm wondering about this link between 95% CI and significant difference.

I apologize for the number of questions and hope that you can provide me with some answers.
Thank you in advance. 
Sincerely

**Comment by 0todd0000** [comment]
Hello!

> Firstly, should sample normality be respected in order to use this analysis?

Partly. Parametric inference assumes normality. Nonparametric inference does not. If the data are non-normally distributed then there may be differences between parametric and nonparametric results, but often these differences are inconsequential, especially when (a) the departures from normality are small, and (b) effects are large. In general it is useful to conduct both parametric and nonparametric analyses and to consider the differences. If the differences are qualitatively similar then the parametric approach's assumption of normality is a negligible one. If the differences are large then the sources of these differences should be considered further.

<br>
<br>

> Also, as with more traditional statistical analyses, are effect size calculations possible? Is there a sample size calculation specific to these analyses?

Yes, effect sizes can be calculated, but effect size calculation is not supported in the current version of **spm1d**. Future versions will support this.

<br>
<br>

> I've also seen on discussion forums that some researchers are integrating all jump trials into their analysis. In fact, I've calculated the average of the 5 jump trials performed and then used this average for the statistics. Is this a mistake?

It depends on the hypothesis. If the hypothesis pertains to the population of all subjects then it is usually adequate to use only means.

<br>
<br>

> Finally, I've had a few discussions with colleagues about confidence intervals. Indeed, some of my data come out significant with the SPM treatment, but visually the graphs show an overlap of the 95% confidence intervals. I'm wondering about this link between 95% CI and significant difference.

It is possible that the CIs and the hypothesis tests do not match. Usually CIs are calculated following a one-sample test. One-sample CIs are generally not the same as a two-sample test.  Please see [this article](https://www.researchgate.net/publication/273576725_Zero-_vs_one-dimensional_parametric_vs_non-parametric_and_confidence_interval_vs_hypothesis_testing_procedures_in_one-dimensional_biomechanical_trajectory_analysis) and in particular Table 3 on Page 17 and Appendix F on Page 39.
