### ISSUE TITLE
Continuous vs categorical variables in CCA and post-hoc regress

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#27]
Dear Todd,

I would like to know if CCA and regress functions in spm1d treats the independent variables as continuous or categorically.

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
The answer is:  continuous.

For regression:
* independent variable: univariate 0D (continuous 0D scalar)
* dependent variable: univariate 0D or 1D (continuous 0D or 1D scalar)

For CCA (as currently implemented in **spm1d**):
* independent variable: univariate 0D (continuous 0D scalar)
* dependent variable: multivariate 0D or 1D (continuous 0D or 1D vector)

In general, CCA can be used with multivariate independent variables, but that is not yet implemented in **spm1d**.  As far as I know the terms "regression" and "CCA" are not used when the independent variables are categorical.

Todd

**Comment by bernard-liew** [comment]
Many thanks Todd:)

Kind regards,
Bernard
