### ISSUE TITLE
SMP1 for comparison one subject and normative data set

### ISSUE THREAD

**Issue by liokainobrega** [0todd0000/spm1d#273]
Our lab conducts research and also provides motion analysis services to the community, focusing on evaluating various movements such as gait, running, and jumping. In our research, we have utilized the SPM technique to compare different groups successfully.

Currently, we are considering employing the SPM method to compare data from an individual patient with our established "normative" dataset. Is the SPM method suitable for such a comparison? What are its potential limitations in this context,?

**Comment by 0todd0000** [comment]
SPM may indeed be suitable for this type of comparison on 1D data provided it is suitable to do a similar comparison with simpler 0D data like body mass. SPM generalizes classical hypothesis techniques from 0D data to 1D (and nD) data, so if a particular hypothesis testing technique is valid for 0D analysis it is likely also valid for nD analysis through SPM.

A t test approach is likely sufficient, especially if there were more than one individual in the sample. For just a single individual it looks like there are methods which slightly modify typical t tests, like the one described in Crawford & Howell (1998). These modifications are not implemented in **spm1d** but it should be possible to implement a valid SPM version of these modifications.

Crawford, J. R., & Howell, D. C. (1998). Comparing an individual's test score against norms derived from small samples. The Clinical Neuropsychologist, 12(4), 482-486.

<br>
<br>

Given the current limitations of **spm1d** I'd recommend using the normative database's mean as the datum and then conduct a one-sample t test. If the normative database is relatively large (>100 or >200 individuals) then its mean will likely be a very good estimate of the population mean, and when the population mean is known a one-sample test is suitable.
