### ISSUE TITLE
Effect sizes for Hotelling's test? 

### ISSUE THREAD

**Issue by The-DanKadlec** [0todd0000/spm1d#277]
Dear Todd, 

I'm running a 2 sample Hotelling's test to evaluate the difference in GRF (Fz and Fy) between 2 cohorts, which is straight forward. Now, is it possible to calculate an effect size to help the interpretation of the T2 statistic? I read about **Partial eta squared** and Multivariate Cohen's d based on the **Mahalanobis distance** as theoretical possibilities for multivariate data, however, I haven't found much in-depth information on either (assumptions, confidence intervals, thresholds, code examples).

Can you provide any guidance if any of these is a feasible approach to help visualise and interpret the data? Or if there generally are or are not ways to add ES for this dataset?

Many thanks for your support, 
Dan

**Comment by 0todd0000** [comment]
Yes, multivariate effect sizes can indeed be calculated, but they are unfortunately not yet supported in **spm1d**.  The test statistic values (in this case: $T^2$-values) exactly follow effect size value patterns across the 1D domain, so I think it may be fine to report the $T^2$-values in lieu of effect size.
