### ISSUE TITLE
Mean & SD Cloud Plot Issue 

### ISSUE THREAD

**Issue by joshuatbland** [0todd0000/spm1d#282]
When I try to create a mean and SD plots I am getting a tringle shaped white section in the SD shading. Has anyone else seen this before or have recommendations for trouble shooting? Thanks. 
<img width="405" alt="Mean_Plot" src="https://github.com/0todd0000/spm1d/assets/137851275/85a2e8df-2fc8-48e6-9696-8a5f4f302fe8">

**Comment by 0todd0000** [comment]
I've not seen this before so something is indeed odd. Thank you for reporting this bug.

Can you please check to see if there are any `nan` values in the array?  It is possible that an `nan` value will cause the plotter to ignore that point.

Can you try plotting just a portion of this?  For example the first 200 points:

```
y1 = y[:,:200]
```

**Comment by joshuatbland** [comment]
Yes, there are some `nan` values at the end of the array. Here is the result of plotting the first 200 points: 
![output_2](https://github.com/0todd0000/spm1d/assets/137851275/bc4ec217-dc88-4519-b092-fefc7b024fc0)

**Comment by 0todd0000** [comment]
I'm closing this issue now because `nan` values are not supported for statistical analysis in **spm1d** but please feel free to repost here if you regard this issue as unresolved.
