### ISSUE TITLE
Shading significance along signal traces

### ISSUE THREAD

**Issue by Andres-Jaramillo** [0todd0000/spm1d#285]
Dear spm1d and Todd
Sorry in advance for the simple question.
Is there a method already implemented in the "plot class" for plotting/shading the significant regions (along x axis) in the plot on top of the signal traces, as in the plots I attach here?
I was trying to find such in the documentation, code, and here in the forum.
Kind regards to all.
Andres

![Screenshot 2024-04-28 210617](https://github.com/0todd0000/spm1d/assets/47823195/87a6ec40-7a9a-40af-8573-b215d20bde56)

**Comment by 0todd0000** [comment]
Hello Andres,
This is not directly supported in the current version of **spm1d** but can be achieved using Matplotlib's [axvspan](https://stackoverflow.com/questions/8270981/how-to-highlight-specific-x-value-ranges). You can use `cluster.endpoints` to get the relevant x-axis positions, for example:

```python
spmi  = spm1d.stats.ttest2(y1, y0).inference(0.05)
x0,x1 = spmi.clusters[0].endpoints
plt.axvspan(x0, x1, color='red', alpha=0.5)
```

**Comment by Andres-Jaramillo** [comment]
Dear Todd,
That just worked perfectly!
Thanks
