### ISSUE TITLE
SPM feature

### ISSUE THREAD

**Issue by sschny** [0todd0000/spm1d#290]
Hello,
I examine two conditions during normal walking, one with and one without a device. I would like to investigate whether the two conditions lead to similar joint angles. Is it possible to carry out an equivalence test in SPM?

Thank you very much for your feedback

**Comment by 0todd0000** [comment]
Hello, thank you for this question. Unfortunately equivalence tests are not yet directly supported in **spm1d**. I have added this to the list of future features here: #45

**Comment by sschny** [comment]
Hello, thank you for the information. Do you have maybe any other ideas on how I could carry out the statistical analysis for my problem?

**Comment by m-a-robinson** [comment]
We are in the process of putting together a manuscript on 1D equivalence as this is something we have been thinking about. We also used a relatively simple 1D confidence interval method in [this paper](https://www.tandfonline.com/doi/full/10.1080/14763141.2020.1860254) though without equivalence bounds. I'd be happy to share some thoughts if you would like to get in touch - my contact details are [here](https://www.ljmu.ac.uk/about-us/staff-profiles/faculty-of-science/sport-and-exercise-sciences/mark-robinson).
