### ISSUE TITLE
interp issue

### ISSUE THREAD

**Issue by gab179** [0todd0000/spm1d#291]
Hi, I'm trying to run an SPM paired ttest analysis following the exemple downloaded on spm1d.org.

When I try to put my datas in the code, I get the error message that "interp is not a recognize parameter".

Here is the code I use : 

[YA,YB] = deal(torque_exc_final_D, torque_exc_final_G);

%(1) Conduct SPM analysis:
spm       = spm1d.stats.ttest_paired(YA, YB);
spmi      = spm.inference(0.05, 'two_tailed', false, 'interp',true);
disp(spmi)

Thank you for your help

**Comment by 0todd0000** [comment]
Hello!  I see that you have posted this issue in the Matlab forum here:
https://github.com/0todd0000/spm1dmatlab/issues/206
so I am closing this issue and will respond there.
