### ISSUE TITLE
How can I input the correct sigma in power1d?

### ISSUE THREAD

**Issue by Xlcandy** [0todd0000/spm1d#294]
Hello, I hope this message finds you well.

I am experiencing some difficulties using power1d, and I'd very appreciate it if you could help me out.

I have collected some kinematic continuous data and I would like to calculate the appropriate sample size using these data. I found that power1d is very suitable for calculating sample size. However, after numerous attempts, I am having difficulty understanding the specific meaning of the **sigma** value in the code. The paper by Pataky TC (2017) (https://peerj.com/articles/cs-125/) mentioned that 'sigma is the effect size as the standard deviation of the ‘signal’ (i.e., noise) under the alternative.' However, I am not sure how to use my continuous data to determine the corresponding effect size.

I have tried modifying the values in the code, here is the modified Python code and the results:

J        = 5    # sample size
Q        = 100  # continuum size

# construct signal geometry (DF_sample is my continuous data):
baseline = power1d.geom.Continuum1D( DF_sample.mean ( axis=0 ) ) 
signal0  = power1d.geom.Null( Q )
signal1  = power1d.geom.GaussianPulse( Q , q=35 , fwhm=10 , amp=15 )

# construct noise model:
noise0   = power1d.noise.Gaussian( J , Q , mu = 0 , sigma = 0.3 )
noise1   = power1d.noise.SmoothGaussian( J , Q , mu = 0 , sigma = 3 , fwhm = 10 )
noise    = power1d.noise.Additive( noise0 , noise1 )

# create data sample models:
model0   = power1d.models.DataSample( baseline, signal0, noise, J=J )
model1   = power1d.models.DataSample( baseline, signal1, noise, J=J )

# create experiment models:
teststat = power1d.stats.t_1sample
emodel0  = power1d.models.Experiment( model0 , teststat )    # null hypothesis
emodel1  = power1d.models.Experiment( model1 , teststat )    # alternative hypothesis

# simulate the experiments:
sim      = power1d.ExperimentSimulator( emodel0 , emodel1 )
results  = sim.simulate( 10000, progress_bar=True )

# visualize the power results:

results.set_coi_radius( 10 ) 
results.plot()

<img width="507" alt="sigma3 capture" src="https://github.com/user-attachments/assets/772c086a-5133-4992-9095-badf6d569ea6">

Here, I set the sample size J to 5 and the sigma for noise1 to 3, resulting in a very high p-value (0.952) and a high power value. However, I don't believe a sample size of 5 is reasonable. When I set the sigma for noise1 to 10, the p-value and power value become very low with J at 5. If I modify J to 15, the p-value and power value return to high levels. Based on my experience, I believe the required sample size for my experimental data would around 15 participants, but I am unsure if setting **sigma** to 10 is correct or what the appropriate value for this sigma should be.

I am looking forward to hearing from you.
Best regards

**Comment by 0todd0000** [comment]
> The paper by Pataky TC (2017) (https://peerj.com/articles/cs-125/) mentioned that 'sigma is the effect size as the standard deviation of the ‘signal’ (i.e., noise) under the alternative.' 

This pertains only to the inflated variance method of Friston et al. (1996). This method is theoretically sound but is quite limited, and incapable of modeling complex effects. I recommend avoiding this method for 1D power analysis in general, especially where a specific, and non-constant 1D effect can be defined.

<br>
<br>

> However, I am not sure how to use my continuous data to determine the corresponding effect size.

I recommend focussing only on the "Software Implementation" section of the PeerJ article. Note that you do not need to explicitly model effect size;  "effect size" is effectively "effect / variance " (i.e., effect divided by variance), and it is much easier to separately model (i) an effect, and (ii) variance than it is to model effect size. For variance I recommend using the `SmoothGaussian` noise with a smoothness and amplitude that approximately matches those in the data you have measured. For the effect you need a hypothesis regarding what type of change would cause you to reject the null hypothesis of no effect.

**Comment by Xlcandy** [comment]
OK, Thank you Todd, I think it worked.
Have a nice day~!
