### ISSUE TITLE
anova1 with different number of row within group

### ISSUE THREAD

**Issue by fablebGitHub** [0todd0000/spm1d#30]
Hi Todd. 

In spm 0.2 , i succeeded to run a spm anova1 with this syntax 
spm1d.stats.anova1( (Y1,Y2,Y3), equal_var=False )
in which, Y1, Y2, Y3 had different size.
It doesn t work now with spm 0.3

is it normal ?

**Comment by 0todd0000** [comment]
Hi Fabien,

Oops!  Thank you for pointing out this bug!

I've fixed the problem and updated the code at github and pypi.  Please download the newest version (0.3.1.4) to fix the problem.

Cheers,

Todd
