### ISSUE TITLE
Post hoc scalar field analysis

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#38]
Dear Todd,

How have you been? I wish to inquire on post hoc scalar field analysis. Say I did a vector field and significance was found in 50% to 90% of gait.

If significance in post hoc at scalar level was found in:

e.g 1) 60-90% (that would be easy and ok to interpret)
e.g 2) 49% to 90%
e.g 3) 50% to 91%
e.g 4) 49% to 91% 

In e.g 2-4, can we say post hoc was significant only in the region where primary analysis was significant? Or if the bounds is exceeded, we should say we cannot interpret the post hoc results.

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

It depends what kind of post hoc analysis you conduct.  If you use no correction for multiple vector components, or if you use a Bonferroni-like correction then it is generally only possible to make qualitative statements regarding the relation between those results and the main multivariate results.  If you use multivariate post hoc procedures then you can be more confident in making quantitative statements regarding precise temporal windows.

In this particular case the discrepancy between the post hoc and main analyses appears to be very small, so the correction employed in post hoc analysis appears to have been appropriate for this particular dataset.  If you refer to the effect window as "approximately 50 to 90%" I can't imagine that a reviewer would object to that wording.  I believe the presence/absence of a suprathreshold cluster is more important than its precise temporal window.

Cheers,

Todd

**Comment by bernard-liew** [comment]
Many thanks Todd.

I had three scalar components and used CCA for the multivariate and Linear regression for each scalar. I used a Bonferroni correction for three post hoc comparisons.

For eg. If my vector field had significance between 49.5% to 93.5% of gait, and my three post-hoc scalar test revealed significance at component 1 ) 41.5% to 44.5%, component 2)	57.5% to 94.5%, component 3) 57.0% to 89.0%

Based on your above comments, it seems I can consider the significance of component 2 and 3. How about component one, when there is no overlapping fields.

In addition, does current spm1d implementation support multivariate post hoc?

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

Currently no post hoc procedures other than Bonferroni are implemented.  We hope to have more comprehensive post hoc options in the next major **spm1d** release.

I would regard all components' post hoc results qualitatively.  The main multivariate test is really the only the one that matters. In other words, if you were interested only in component 1 then you would have designed an experiment targeting only component 1 and would have analyzed only component 1. In this experiment the dependent variable was multivariate so the multivariate result itself is most important. So I would regard the post hoc results as useful mainly for formulating subsequent hypotheses to be tested on independent datasets and/or independent experiments.

If you wish to probe the result a little further you could look plot:
* *x* vs. component 1
* *x* vs. component 2
* *x* vs. component 3

at two separate time instants:

* the instant of the maximum X2 value
* the instant of component 1's maximum t value

where *x* is the independent variable. That will give you a sense of the strength of correlations the tests represent.

Cheers,

Todd
