### ISSUE TITLE
Sphericity

### ISSUE THREAD

**Issue by Kneerav** [0todd0000/spm1d#47]
Hi Todd, 

First off, thanks for your terrific python package. I have read almost all of your papers related to SPM, and I had a couple of queries regarding the Python package that I was hoping you could answer. 

In short, I am comparing 3D kinematics and kinetics of participants across 5 different tasks. I am primarily interested in the knee joint injury implications, but am also looking at the hip and ankle joints. 

My plan is to conduct a repeated measures ANOVA (is there a vector field equivalent? Can Hotelling's be applied for multiple groups?) for each variable of interest for the 5 tasks, then conduct post-hoc paired t-tests with a Bonferroni correction for the comparisons. If this seems reasonable to you, I guess I would ask:
1.Given that the non-sphericity correction is approximate and has yet to be verified, what does this mean for publication outcomes? Would you recommend I use another method if sphericity is violated?
2.Is there a simple way to test for sphericity with these sorts of datasets? (Is there an SPM specific method for assumption testing e.g. sphericity or normality at each node?)
3.Finally, is it simply good practice to interpolate to ~100 data points? Some of my data is based on time, thus each participants data already has the same number of nodes. My concern is that the low number of time nodes (sometimes less than 20) might be influencing RFT related corrections. 

Hope that all makes sense. Again, any help you can provide would be much appreciated given your expertise in the area.

**Comment by 0todd0000** [comment]
Please find a response in **spm1d**'s MATLAB forum:
https://github.com/0todd0000/spm1dmatlab/issues/19

Apologies for confusions associated with the two separate forums.

Todd
