### ISSUE TITLE
Error for normality in matlab

### ISSUE THREAD

**Issue by SinaDavid** [0todd0000/spm1d#59]
Hey Todd,
I just tried the new normality method and get the following error code (:

No appropriate method, property, or field residuals for class spm1d.stats.spm.SPM.
Error in spm1d.stats.spm.SPMi (line 42)
            self.residuals    = spm.residuals;

Error in spm1d.stats.spm.SPM/inference (line 88)
            spmi         = spm1d.stats.spm.SPMi(self, alpha, zstar, p_set, p, two_tailed, clusters);

Error in ex1d_ttest2 (line 15)
spmi      = spm.inference(0.05);

Do you have any idea whats the problem?

Best regards,
Sina

**Comment by 0todd0000** [comment]
Hi Sina,

Thank you for reporting this error.  I can't seem to reproduce it, so please send some more details...

Are you running the example script: **./spm1d/examples/normality/1d/ex_ttest2.py** or are you using your own script?

If you're using your own script please copy it into your reply here. 

Todd

**Comment by 0todd0000** [comment]
Hi again Sina,

I just realized that you're using the MATLAB version of **spm1d** and and not the Python version.  This forum is for Python issues, so please find that I've replicated this issue in the MATLAB forum at the link below.

https://github.com/0todd0000/spm1dmatlab/issues/30

I'll close this issue in the Python forum, please use the link above to continue the discussion.

Cheers,
Todd
