### ISSUE TITLE
Bayesian SPM

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#64]
Dear Todd,

Happy New Year, how have you been. I am writing up a piece of paper using a two group, pre-post design on 2 training methods on jumping height and power. I am planning to do a bayesian analysis for the discrete measure of jump height. I am wondering if bayesian spm is available for joint power waveform analysis. If codes are not available publicly yet (which I think so), would you be open to collaboration?

Just an inquiry. Happy to hear your thoughts.

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

That's correct:  Bayesian inference is currently in-development.  It will likely not be available publicly for at least another year.

I'm certainly open to collaboration, but my timeline may not be suitable if you need to finish the paper soon.  Until May I have some pressing grant-related tasks that I need to complete, so if you can wait until about June to start then I'd be happy to discuss collaboration.  If you need to get started before then I'd suggest taking a look at papers like the ones below, and/or maybe trying out **SPM-12 ** (www.fil.ion.ucl.ac.uk/spm/software/spm12/).  If you've not used **SPM-12** before, note that it's much more powerful than **spm1d** and already supports a variety of Bayesian analysis techniques.  However, it's a bit more difficult to get started with, especially for 1D data.  Although **SPM-12** does indeed support 1D data analysis, it's not very obvious how to organize the data.

Friston, K. J., & Penny, W. (2003). Posterior probability maps and SPMs. NeuroImage, 19(3), 1240–1249. http://doi.org/10.1016/S1053-8119(03)00144-7

Sidén, P., Eklund, A., Bolin, D., & Villani, M. (2016). Fast Bayesian Whole-Brain fMRI Analysis with Spatial 3D Priors. NeuroImage, 1–35. http://doi.org/10.1016/j.neuroimage.2016.11.040

Woolrich, M. W. (2012). Bayesian inference in FMRI. NeuroImage, 62(2), 801–810. http://doi.org/10.1016/j.neuroimage.2011.10.047

**Comment by bernard-liew** [comment]
Hi Todd,

I totally understand. I will have a look at spm12 first, and will probably update you further via your email on opportunities for collaboration.

Kind regards,
Bernard
