### ISSUE TITLE
Data template

### ISSUE THREAD

**Issue by gabrielmoisan** [0todd0000/spm1d#72]
Dr Pataky,
I am currently trying to analyze data in Python using SPM1D. However, I think my dataset are not in the right format. I used MatLab to reorganize the data before loading them in Python. Is it possible for you to send a template of data that I could use to guide me. I am trying to do a 2x2 repeated measures ANOVA.
Thank you for your time, 
Gabriel Moisan
Université du Québec à Trois-Rivières, Canada

**Comment by m-a-robinson** [comment]
Hello Gabriel,

[This document](https://www.dropbox.com/s/ia1mvenjatmklu5/Data%20formatting%20for%20SPM%20analysis.pdf?dl=0) may be of use to describe general formatting for SPM analysis.
Also [this previous issue ](https://github.com/0todd0000/spm1d/issues/16)is related to your question.  
Another good way of judging appropriate data structuring is to run the example script e.g. spm1d.stats.anova2rm and to look at the structure of the variables in there.

Hopefully one or a combination of those sources will solve your problem.

Regards
Mark

**Comment by gabrielmoisan** [comment]
Hello Mark,
Thank you for your time. I think this will solve my problem. I'll keep you posted if it does not work.
Gabriel
