### ISSUE TITLE
> 1D dependent data (more question than issue)

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#73]
Hi Todd,

How have you been? I refer to the question already posed (https://github.com/0todd0000/spm1d/issues/70). 

I am thinking of analysing signals from two spatial dimensions (X, Y) on a high density EMG grid, coupled with the time domain makes it 3D? How is nD data analysis different from multivariate SPM? I assume it is the model of randomness. The reason I ask is simple. In knee angle for example, it can naturally be decomposed into XYZ coordinates. It seems similar to having multiple signals along a grid, which can be naturally thought of as (x1,x,2,x3,xn..) and (y1,y2,y3,yn..) coordinates.

At first I thought that multivariate analysis is like analyzing different colours of the same fruit, and nD data different fruits. Again I think it is the assumption used in modelling the randomness.

PS: Any room in a collaboration with you or any of your co-authors to learn nD SPM, in a paper?

Regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,
A similar discussion was just raised on **spm1d**'s MATLAB forum here:
[**spm1d** MATLAB issue 61:  spm1d on mesh (3D)](https://github.com/0todd0000/spm1dmatlab/issues/61)
If that doesn't answer your questions please let me know.
Todd

**Comment by bernard-liew** [comment]
Hi Todd,

Many thanks for the link. It answer some question, but perhaps, I was looking more for the theoretical why. Why is a 3D neuroimaging data for example different to a 3D knee angle? What in the data lends the former unsuitable for a multivariate analysis, and the latter suitable?

Kind regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

To understand why, consider that:

* There are two dimensionalities: continuum dimensionality (*m*) and dependent variable dimensionality (*n*)
* Multivariate analysis is used when *n*>1

In many Biomechanics experiments measured data may be regarded as *m*D*n*D continua. For example:

* Body mass:  **0D1D**   (unless considering continuous body mass changes over time)
* Instantaneous knee angle at impact:  **0D3D**
* Knee flexion angle during stance phase:  **1D1D**
* Knee posture during stance phase:  **1D6D**  (*n*: three displacements and three angles)
* Maximum plantar pressure distribution: **2D1D**
* Plantar pressure during stance phase: **3D1D** (*m*: 2D space + 1D time)
* Von mises stress in bone:  **3D1D**
* Stress tensor in bone:  **3D6D**

In Neuroimaging there are two common examples:

* Brain deformation field:  **3D3D**  (i.e. a 3D vector at each point in the brain representing the deformation needed to morphologically register one person's brain to another)
* BOLD response in brain:  **4D1D**  (i.e. a 1D signal it each point in 3D space + 1D time)

Note that the physical nature of the dependent variable is identical at all points in the continuum.  So in the second example above (Knee angle during stance phase), the physical meaning of "knee angle" is constant throughout the 1D continuum.  Similarly, in the second-last Biomechanics example (Von mises stress in bone), the physical meaning of Von mises stress is identical at all points in the 3D continuum.

In all of the examples above, univariate analyses are appropriate for *n*=1 and multivariate analyses are appropriate for *n*>1.

Todd

**Comment by 0todd0000** [comment]
Preliminary support for 2D data analysis has been added to **spm1d**!
[Example 2D analysis (Python)](http://www.spm1d.org/doc/Stats2D/ex2d.html)
[Example 2D analysis (MATLAB)](http://www.spm1d.org/doc/Stats2D/ex2d_matlab.html)
