### ISSUE TITLE
Procedure for Data Entering

### ISSUE THREAD

**Issue by meteor77** [0todd0000/spm1d#80]
Hi Todd,

I was curious as to know what is the valid method for entering our data. I have 30 subjects and each subject has registered 5 gait cycles. Do I take 5 cycles and calculate the mean and standard deviation so that each person would have 1 set of data associated with them (total cycles = 30), or should I consider entering every single cycle regardless of the intra-subject factor (total cycles = 150)? 

One of my colleagues conducted the test for each of these situations mentioned and in each case, although the threshold value was quite similar, he got different results regarding the rejection of the null hypothesis. In the case of using single set data (which is the mean of 5 cycles) for each person, the null hypothesis when conducting the t-test was not rejected; whereas when entering 5 cycles for each person the null hypothesis was rejected.

Much appreciated.

**Comment by 0todd0000** [comment]
Hi,
Adding all trials is OK only for repeated-measures ANOVA. More specifically, you can include individual trials only if it doesn't increase the degrees of freedom (DF). Adding all trials to a t test, for example, will greatly increase the DF, and thus lower the critical t value. If there are 30 subjects and 5 trials, a t test will regard the 150 observations as 150 separate subjects.  In contrast, repeated-measures ANOVA will correctly recognize that there are still only 30 unique subjects.
Todd
