### ISSUE TITLE
Not Issue: a question on suitability (Coherence analysis data)

### ISSUE THREAD

**Issue by bernard-liew** [0todd0000/spm1d#82]
Dear Todd, 

How have you been? My colleagues have some EMG data, using coherence analysis on the frequency domain. So the x-axis is really frequency bands, and the Y, a % measure of coherence. Can I ask is SPM as a methodology suitable? I have really used it for time-domain analysis. If it is suitable, and can spm1D deal with such analysis, or only SPM12?

Kind regards,
Bernard

**Comment by 0todd0000** [comment]
Hi Bernard,

I'm not familiar with coherence analysis so I'm not sure if SPM is suitable, but here are some thoughts:

* SPM is generally suitable for any continuous measurement domain (time, space, etc.) so it might be OK for frequency domain analysis.  However, as far as I know this use has not been validated in the literature so it would require simulation of controlled frequency properties to validate.  I suspect that the validity might depend on the length of the time series used to construct the power spectra.

* Power spectra are distributions, so they can be analyzed using distribution comparison techniques. These test for overall distribution equivalence, so if you're not concerned about particular frequency bands this might be a good approach. NeuroSpec (www.neurospec.org) is useful for this type of analysis.  If you are only interested in a particular frequency band (e.g. 5 to 10 Hz) I think it might be suitable to analyze the estimated power for that band by extracting one scalar from each spectrum (e.g. the mean power in the band of interest), then use standard 0D approaches like ANOVA.

Todd

**Comment by bernard-liew** [comment]
Thank you Todd for the clarification and link, that is helpful. I shall close this question.

Cheers,
Bernard
