### ISSUE TITLE
Reporting SPM in manuscript

### ISSUE THREAD

**Issue by gabrielmoisan** [0todd0000/spm1d#85]
Hi Todd,
I used the normality python code to assess normality of my data (ANOVA1rm) and to evaluate the differences between my experimental conditions with the python code (ANOVA1rm non-parametric).
I am not sur how to report this in the manuscript. 
1. What is the normality test used? Chi-square?
2. What is the non-parametric test equivalent to ANOVA1rm used in the code?
3. Can you point me toward a paper that reported this method to take a look at it?
Thank you for your time,
Gabriel

**Comment by 0todd0000** [comment]
Hi Gabriel,

1.  D’Agostino-Pearson test (D’agostino and Belanger, 1990). We have validated use of this test for 1D data but have not yet published it.

2. Permutation test (Nichols and Holmes 2002).  This approach is described for 1D data as part of Pataky et al. (2015)

3. The papers cited above are:
- D'agostino RB, Belanger A. A suggestion for using powerful and informative tests of normality. The American Statistician. 1990 Nov 1;44(4):316-21.
- Nichols, T. E. and Holmes, A. P. 2002. Nonparametric permutation tests for functional neuroimaging a primer with examples, Human Brain Mapping 15(1), 1–25.
- Pataky TC, Vanrenterghem J, Robinson MA. Zero-vs. one-dimensional, parametric vs. non-parametric, and confidence interval vs. hypothesis testing procedures in one-dimensional biomechanical trajectory analysis. Journal of biomechanics. 2015 May 1;48(7):1277-85.

Cheers,
Todd

**Comment by gabrielmoisan** [comment]
Hi Todd,
Thank you for the helpful answer. I have a follow-up question. Just to make sure I understand the non-parametric test. Are the following statements still true?

The steps to complete the non-parametric test are:
1. To compute the SPM at each point of the normalized stride curves. 
2. Estimate the temporal data smoothness based on the average temporal gradient. 
3. Calculate the SPM threshold above which α =5% of the data would be expected to reach, had the test statistic trajectory resulted from an equivalently smooth random process. 
4. Calculate the individual probability that each supra-threshold cluster could have resulted from an equivalently smooth random process
Thank you for your time,
Gabriel

**Comment by 0todd0000** [comment]
Hi Gabriel,

Yes, those statements are still true with two minor exceptions...

> 1. To compute the SPM at each point of the normalized stride curves.

The test statistic (e.g. t value) is computed at each time point.  The SPM / SnPM is the test statistic trajectory (or continuum, or field, or waveform). 

> 2. Estimate the temporal data smoothness based on the average temporal gradient.

Non-parametric SPM (SnPM) doesn't calculate smoothness.  Smoothness (as embodied in the FWHM) is a parameter that is used only in parametric inference.  SnPM instead deals with smoothness implicitly, through permutation.

The third and fourth points are fine, provided it is clear that smoothness is implicit rather than explicit in SnPM analysis.

Todd

**Comment by gabrielmoisan** [comment]
Hi Todd,
Thank you for your time. Helpful, as always!
Gabriel
