### ISSUE TITLE
circular inferece

### ISSUE THREAD

**Issue by zof1985** [0todd0000/spm1d#89]
Hi Todd,

Looking at the smp1d documentation, I was not able to find information about how the "circular" and the "interpolation" options works in parametric and non-parametric inference. Could you please indicate where I can find it and/or some references that I can study to understand how it work? It would also be great if you could provide a brief description about how it is implemented.

Many thanks,
Luca.

**Comment by 0todd0000** [comment]
Hi Luca,

Sorry for the unclear documentation! Descriptions of "circular" and "interpolation" are available only through the "New Features" sections here:

Circular:
http://www.spm1d.org/NewFeatures.html#circular-fields

Interpolation:
http://www.spm1d.org/NewFeatures.html#cluster-interpolation

If these descriptions are unclear please let me know.

Todd

**Comment by 0todd0000** [comment]
Yes, linear.  Other interpolation schemes (e.g. spline) are more accurate, but the probabilistic difference between linear and nonlinear interpolation is negligible.

**Comment by zof1985** [comment]
Thank you very much
